import { afterAll, beforeAll, describe, expect, it } from "vitest";
import request from "supertest";
import { createApp } from "../../app.js";
import { createTestPrismaClient } from "../../lib/test-database.js";
import { hashPassword } from "../auth/auth.service.js";

const marker=`phase7a1-service-${Date.now()}`, password="phase7a1 secure password";
const db=createTestPrismaClient(), app=createApp({database:db});
const ids:string[]=[];const agents={} as Record<"ADMIN"|"LAWYER"|"STAFF",ReturnType<typeof request.agent>>;let adminId="",inactiveId="",createdId="";
const origin="http://localhost:3000";
beforeAll(async()=>{for(const role of ["ADMIN","LAWYER","STAFF"] as const){const user=await db.user.create({data:{email:`${marker}.${role.toLowerCase()}@example.test`,name:`${marker} ${role}`,role,passwordHash:await hashPassword(password)}});ids.push(user.id);if(role==="ADMIN")adminId=user.id;const agent=request.agent(app);expect((await agent.post("/api/v1/auth/login").send({email:user.email,password})).status).toBe(200);agents[role]=agent;}const inactive=await db.service.create({data:{slug:`${marker}-inactive`,name:`${marker} inactive`,description:"Controlled inactive service.",isActive:false,sortOrder:999999}});inactiveId=inactive.id;},30_000);
afterAll(async()=>{const serviceIds=[inactiveId,createdId].filter(Boolean);await db.auditLog.deleteMany({where:{entity:"Service",entityId:{in:serviceIds}}});await db.consultation.deleteMany({where:{serviceId:{in:serviceIds}}});await db.service.deleteMany({where:{id:{in:serviceIds}}});await db.auditLog.deleteMany({where:{userId:{in:ids}}});await db.session.deleteMany({where:{userId:{in:ids}}});await db.user.deleteMany({where:{id:{in:ids}}});await db.$disconnect();});
describe("admin services API",()=>{
 it("enforces ADMIN-only safe list, pagination, search, filtering, and sorting",async()=>{expect((await request(app).get("/api/v1/admin/services")).status).toBe(401);expect((await agents.LAWYER.get("/api/v1/admin/services")).status).toBe(403);expect((await agents.STAFF.get("/api/v1/admin/services")).status).toBe(403);const listed=await agents.ADMIN.get(`/api/v1/admin/services?search=${marker}&isActive=false&sortBy=slug&sortOrder=asc&page=1&limit=1`);expect(listed.status).toBe(200);expect(listed.body.data.pagination).toMatchObject({page:1,limit:1,total:1});expect(listed.body.data.items[0]).toMatchObject({id:inactiveId,isActive:false});expect(listed.body.data.items[0]).not.toHaveProperty("description");expect((await agents.ADMIN.get("/api/v1/admin/services?page=0")).body.error.code).toBe("VALIDATION_ERROR");expect((await agents.ADMIN.get("/api/v1/admin/services?sortBy=passwordHash")).body.error.code).toBe("VALIDATION_ERROR");expect((await agents.ADMIN.get(`/api/v1/admin/services?search=${marker}-none`)).body.data.items).toHaveLength(0);});
 it("creates, reads, and updates a controlled service with safe audit records",async()=>{const invalid=await agents.ADMIN.post("/api/v1/admin/services").set("Origin",origin).send({slug:"Not Safe",name:" ",description:"x"});expect(invalid.status).toBe(400);const unknown=await agents.ADMIN.post("/api/v1/admin/services").set("Origin",origin).send({slug:`${marker}-unknown`,name:"Unknown",description:"Description",extra:true});expect(unknown.status).toBe(400);const created=await agents.ADMIN.post("/api/v1/admin/services").set("Origin",origin).send({slug:`${marker}-created`,name:`${marker} Created`,description:"Controlled service description.",sortOrder:7});expect(created.status).toBe(201);createdId=created.body.data.id;expect(created.body.data).toMatchObject({id:createdId,slug:`${marker}-created`,isActive:true,sortOrder:7});expect((await db.service.findUnique({where:{id:createdId}}))?.name).toBe(`${marker} Created`);expect((await db.auditLog.findFirst({where:{entityId:createdId,action:"SERVICE_CREATED"}}))?.metadata).toMatchObject({slug:`${marker}-created`});const duplicate=await agents.ADMIN.post("/api/v1/admin/services").set("Origin",origin).send({slug:`${marker}-created`,name:"Duplicate",description:"Duplicate description"});expect(duplicate.status).toBe(409);expect(duplicate.body.error.code).toBe("SERVICE_SLUG_EXISTS");const detail=await agents.ADMIN.get(`/api/v1/admin/services/${createdId}`);expect(detail.status).toBe(200);expect(detail.body.data).toMatchObject({id:createdId,description:"Controlled service description."});expect((await agents.LAWYER.get(`/api/v1/admin/services/${createdId}`)).status).toBe(403);expect((await agents.ADMIN.get("/api/v1/admin/services/ck000000000000000000000000")).body.error.code).toBe("SERVICE_NOT_FOUND");const update=await agents.ADMIN.patch(`/api/v1/admin/services/${createdId}`).set("Origin",origin).send({name:`${marker} Updated`,sortOrder:8});expect(update.status).toBe(200);expect((await db.service.findUnique({where:{id:createdId}}))?.name).toBe(`${marker} Updated`);expect((await db.auditLog.findFirst({where:{entityId:createdId,action:"SERVICE_UPDATED"}}))?.metadata).toMatchObject({changedFields:["name","sortOrder"]});expect((await agents.ADMIN.patch(`/api/v1/admin/services/${createdId}`).set("Origin",origin).send({slug:"changed"})).status).toBe(400);expect((await agents.STAFF.patch(`/api/v1/admin/services/${createdId}`).set("Origin",origin).send({name:"Denied"})).status).toBe(403);});
 it("manages active status without misleading no-op audit and protects public booking",async()=>{const before=await db.auditLog.count({where:{entityId:createdId,action:"SERVICE_DISABLED"}});const disabled=await agents.ADMIN.patch(`/api/v1/admin/services/${createdId}/status`).set("Origin",origin).send({isActive:false});expect(disabled.status).toBe(200);expect((await db.service.findUnique({where:{id:createdId}}))?.isActive).toBe(false);expect((await db.auditLog.findFirst({where:{entityId:createdId,action:"SERVICE_DISABLED"}}))?.metadata).toMatchObject({oldIsActive:true,newIsActive:false});const same=await agents.ADMIN.patch(`/api/v1/admin/services/${createdId}/status`).set("Origin",origin).send({isActive:false});expect(same.status).toBe(200);expect(await db.auditLog.count({where:{entityId:createdId,action:"SERVICE_DISABLED"}})).toBe(before+1);const publicServices=await request(app).get("/api/v1/services");expect(publicServices.body.data.some((service:{id:string})=>service.id===createdId)).toBe(false);const consultationsBefore=await db.consultation.count({where:{serviceId:inactiveId}});const booking=await request(app).post("/api/v1/consultations").send({serviceId:inactiveId,name:"Controlled Client",email:"controlled@example.test",phone:"+971501234567",preferredDate:"2099-12-31",preferredTime:"09:00 AM",website:""});expect(booking.status).toBe(404);expect(booking.body.error.code).toBe("SERVICE_NOT_FOUND");expect(await db.consultation.count({where:{serviceId:inactiveId}})).toBe(consultationsBefore);const enabled=await agents.ADMIN.patch(`/api/v1/admin/services/${createdId}/status`).set("Origin",origin).send({isActive:true});expect(enabled.status).toBe(200);expect((await db.auditLog.findFirst({where:{entityId:createdId,action:"SERVICE_ENABLED"}}))?.metadata).toMatchObject({oldIsActive:false,newIsActive:true});expect((await agents.LAWYER.patch(`/api/v1/admin/services/${createdId}/status`).set("Origin",origin).send({isActive:false})).status).toBe(403);expect((await agents.ADMIN.patch(`/api/v1/admin/services/${createdId}/status`).set("Origin","https://evil.example").send({isActive:false})).status).toBe(403);expect(adminId).not.toBe("");});
});
