import { Router } from "express";
import type { Router as ExpressRouter } from "express";
import type { PrismaClient } from "@prisma/client";
import { adminServiceCreateSchema, adminServicesListQuerySchema, adminServiceStatusSchema, adminServiceUpdateSchema } from "@hhlawyer/validation";
import { AppError } from "../../middleware/error-handler.js";
import { requireApprovedOrigin } from "../../middleware/origin.js";
import { requireAuth, requirePermission, type AuthRequest } from "../auth/auth.routes.js";

const listSelect={id:true,slug:true,name:true,isActive:true,sortOrder:true,createdAt:true,updatedAt:true} as const;
const detailSelect={...listSelect,description:true} as const;
function routeId(value:string|string[]){return Array.isArray(value)?value[0]:value;}
function isUnique(error:unknown){return typeof error==="object"&&error!==null&&"code" in error&&(error as {code?:string}).code==="P2002";}
function notFound(){return new AppError(404,"SERVICE_NOT_FOUND","Service was not found.");}

export function createAdminServicesRouter(database:PrismaClient):ExpressRouter{
  const router=Router();
  router.use("/admin/services",requireAuth(database));
  router.get("/admin/services",requirePermission("SERVICE_READ"),async(req,res,next)=>{const parsed=adminServicesListQuerySchema.safeParse(req.query);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid service query."));const value=parsed.data;const where={...(value.isActive===undefined?{}:{isActive:value.isActive}),...(value.search?{OR:["name","slug"].map(field=>({[field]:{contains:value.search,mode:"insensitive" as const}}))}:{})};try{const [items,total]=await Promise.all([database.service.findMany({where,skip:(value.page-1)*value.limit,take:value.limit,orderBy:{[value.sortBy]:value.sortOrder},select:listSelect}),database.service.count({where})]);res.json({success:true,data:{items,pagination:{page:value.page,limit:value.limit,total,totalPages:Math.ceil(total/value.limit)}}});}catch{next(new AppError(500,"DATABASE_ERROR","Unable to load services."));}});
  router.get("/admin/services/:id",requirePermission("SERVICE_READ"),async(req,res,next)=>{try{const service=await database.service.findUnique({where:{id:routeId(req.params.id)},select:detailSelect});if(!service)return next(notFound());res.json({success:true,data:service});}catch{next(new AppError(500,"DATABASE_ERROR","Unable to load service."));}});
  router.post("/admin/services",requireApprovedOrigin,requirePermission("SERVICE_MANAGE"),async(req:AuthRequest,res,next)=>{const parsed=adminServiceCreateSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid service payload."));try{const service=await database.$transaction(async tx=>{const created=await tx.service.create({data:parsed.data,select:detailSelect});await tx.auditLog.create({data:{userId:req.auth!.id,action:"SERVICE_CREATED",entity:"Service",entityId:created.id,metadata:{slug:created.slug,isActive:created.isActive}}});return created;});res.status(201).json({success:true,data:service});}catch(error){next(isUnique(error)?new AppError(409,"SERVICE_SLUG_EXISTS","A service with this slug already exists."):new AppError(500,"DATABASE_ERROR","Unable to create service."));}});
  router.patch("/admin/services/:id",requireApprovedOrigin,requirePermission("SERVICE_MANAGE"),async(req:AuthRequest,res,next)=>{const parsed=adminServiceUpdateSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid service payload."));try{const service=await database.$transaction(async tx=>{const current=await tx.service.findUnique({where:{id:routeId(req.params.id)},select:detailSelect});if(!current)throw notFound();const changedFields=(["name","description","sortOrder"] as const).filter(key=>parsed.data[key]!==undefined&&current[key]!==parsed.data[key]);if(!changedFields.length)return current;const updated=await tx.service.update({where:{id:current.id},data:parsed.data,select:detailSelect});await tx.auditLog.create({data:{userId:req.auth!.id,action:"SERVICE_UPDATED",entity:"Service",entityId:updated.id,metadata:{changedFields}}});return updated;});res.json({success:true,data:service});}catch(error){next(error instanceof AppError?error:new AppError(500,"DATABASE_ERROR","Unable to update service."));}});
  router.patch("/admin/services/:id/status",requireApprovedOrigin,requirePermission("SERVICE_MANAGE"),async(req:AuthRequest,res,next)=>{const parsed=adminServiceStatusSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid service status."));try{const service=await database.$transaction(async tx=>{const current=await tx.service.findUnique({where:{id:routeId(req.params.id)},select:detailSelect});if(!current)throw notFound();if(current.isActive===parsed.data.isActive)return current;const updated=await tx.service.update({where:{id:current.id},data:{isActive:parsed.data.isActive},select:detailSelect});await tx.auditLog.create({data:{userId:req.auth!.id,action:updated.isActive?"SERVICE_ENABLED":"SERVICE_DISABLED",entity:"Service",entityId:updated.id,metadata:{oldIsActive:current.isActive,newIsActive:updated.isActive}}});return updated;});res.json({success:true,data:service});}catch(error){next(error instanceof AppError?error:new AppError(500,"DATABASE_ERROR","Unable to update service status."));}});
  return router;
}
