"use client";

import { useParams } from "next/navigation";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { useLocale } from "@/components/providers/LocaleProvider";
import { formatLocaleDateTime } from "@/i18n/format";
import { errorMessage, messages } from "@/i18n/messages";
import { currentUser } from "@/lib/api/auth";
import { ApiClientError } from "@/lib/api/client";
import { adminServicesKeys, getAdminService, updateAdminService, updateAdminServiceStatus } from "@/lib/api/admin-services";

export default function ServiceDetailPage() {
  const locale = useLocale(); const en = locale === "en"; const t = messages[locale]; const { id } = useParams<{ id: string }>(); const client = useQueryClient();
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [sortOrder, setSortOrder] = useState(0); const [dirty, setDirty] = useState(false); const [disableOpen, setDisableOpen] = useState(false); const [message, setMessage] = useState("");
  const me = useQuery({ queryKey: ["auth", "me"], queryFn: currentUser, retry: false }); const service = useQuery({ queryKey: adminServicesKeys.detail(id), queryFn: () => getAdminService(id), enabled: me.data?.user.role === "ADMIN" }); const item = service.data;
  const formName = dirty ? name : item?.name ?? ""; const formDescription = dirty ? description : item?.description ?? ""; const formSortOrder = dirty ? sortOrder : item?.sortOrder ?? 0; const refresh = () => client.invalidateQueries({ queryKey: adminServicesKeys.all }); const fail = (error: unknown) => setMessage(errorMessage(locale, error instanceof ApiClientError ? error.error.code : undefined));
  const edit = useMutation({ mutationFn: () => updateAdminService(id, { name: formName, description: formDescription, sortOrder: formSortOrder }), retry: false, onSuccess: async (updated) => { setName(updated.name); setDescription(updated.description); setSortOrder(updated.sortOrder); setDirty(false); setMessage(en ? "Service updated successfully." : "تم تحديث الخدمة بنجاح."); await refresh(); }, onError: fail });
  const status = useMutation({ mutationFn: (isActive: boolean) => updateAdminServiceStatus(id, { isActive }), retry: false, onSuccess: async (updated) => { setDisableOpen(false); setMessage(updated.isActive ? (en ? "Service enabled successfully." : "تم تفعيل الخدمة بنجاح.") : (en ? "Service disabled successfully." : "تم تعطيل الخدمة بنجاح.")); await refresh(); }, onError: fail });
  if (me.isLoading || service.isLoading) return <p className="p-8" aria-busy="true">{en ? "Loading…" : "جارٍ التحميل…"}</p>;
  if (!me.data || me.data.user.role !== "ADMIN") return <p className="p-8" role="alert">{en ? "You do not have permission to manage services." : "ليس لديك صلاحية لإدارة الخدمات."}</p>;
  if (!item) return <p className="p-8" role="alert">{en ? "The service could not be found or loaded." : "الخدمة غير موجودة أو تعذر تحميلها."}</p>;
  const busy = edit.isPending || status.isPending; const beginEdit = () => { if (!dirty) { setName(item.name); setDescription(item.description); setSortOrder(item.sortOrder); setDirty(true); } };
  return <section className="mx-auto max-w-4xl space-y-5 p-8"><header><h1 className="text-3xl font-bold">{t.admin.serviceDetails}</h1><p>{item.name}</p></header><section className="rounded border p-4"><h2>{en ? "Service information" : "بيانات الخدمة"}</h2><dl className="grid gap-2"><dt>Slug</dt><dd dir="ltr"><bdi>{item.slug}</bdi></dd><dt>{t.common.status}</dt><dd>{item.isActive ? t.common.active : t.common.inactive}</dd><dt>{t.admin.createdAt}</dt><dd>{formatLocaleDateTime(item.createdAt, locale)}</dd><dt>{en ? "Last updated" : "آخر تحديث"}</dt><dd>{formatLocaleDateTime(item.updatedAt, locale)}</dd></dl><p>{en ? "The public slug is immutable to protect published links." : "الرابط العام ثابت لحماية الروابط المنشورة ولا يمكن تغييره."}</p></section><section className="rounded border p-4"><h2>{en ? "Edit service" : "تعديل الخدمة"}</h2><form data-testid="service-edit" onSubmit={(event) => { event.preventDefault(); edit.mutate(); }} className="grid gap-3"><label>{en ? "Service name" : "اسم الخدمة"}<input required maxLength={160} value={formName} onChange={(event) => { beginEdit(); setName(event.target.value); }} className="text-black" /></label><label>{t.admin.description}<textarea required maxLength={4000} value={formDescription} onChange={(event) => { beginEdit(); setDescription(event.target.value); }} className="text-black" /></label><label>{t.admin.sort}<input type="number" min={0} value={formSortOrder} onChange={(event) => { beginEdit(); setSortOrder(Number(event.target.value)); }} className="text-black" /></label><button type="submit" disabled={busy}>{t.admin.update}</button></form></section><section className="rounded border p-4"><h2>{en ? "Service status" : "حالة الخدمة"}</h2>{item.isActive ? <button data-testid="service-status-action" disabled={busy} onClick={() => setDisableOpen(true)}>{en ? "Disable service" : "تعطيل الخدمة"}</button> : <button data-testid="service-status-action" disabled={busy} onClick={() => status.mutate(true)}>{en ? "Enable service" : "تفعيل الخدمة"}</button>}{disableOpen ? <div data-testid="service-disable-dialog" role="alertdialog" aria-modal="true" aria-labelledby="disable-service-title" className="mt-3 rounded border p-3"><p id="disable-service-title">{en ? "The service will be hidden from the public list and unavailable for new bookings. Existing bookings remain preserved." : "لن تظهر الخدمة في القائمة العامة ولن تكون متاحة للحجوزات الجديدة، لكن الحجوزات السابقة ستبقى محفوظة."}</p><button data-testid="service-disable-confirm" disabled={busy} onClick={() => status.mutate(false)}>{en ? "Confirm disable" : "تأكيد التعطيل"}</button><button data-testid="service-disable-cancel" disabled={busy} onClick={() => setDisableOpen(false)}>{t.common.cancel}</button></div> : null}</section><p aria-live="polite" role={edit.isError || status.isError ? "alert" : undefined}>{message}</p></section>;
}
