import { randomUUID } from "node:crypto";
import { expect, test, type Page } from "@playwright/test";
import { createTestPrismaClient } from "../../api/src/lib/test-database";
import { hashPassword } from "../../api/src/modules/auth/auth.service";
import { selectValue } from "./select-helpers";

test.describe.configure({ mode: "serial" });
const db = createTestPrismaClient(); const marker = `phase6c3_users_${randomUUID()}`; const password = "phase6c2 secure password"; const nextPassword = "phase6c2 reset password";
const ids: string[] = []; let adminId = ""; let staffId = ""; let lawyerId = "";
async function login(page: Page, email: string) { await page.goto("/admin/login"); await page.getByLabel("البريد الإلكتروني").fill(email); await page.getByLabel("كلمة المرور").fill(password); const response = page.waitForResponse((value) => value.url().endsWith("/auth/login") && value.request().method() === "POST"); await page.getByRole("button", { name: "تسجيل الدخول" }).click(); expect((await response).status()).toBe(200); await page.waitForURL(/\/admin$/); }
test.beforeAll("create controlled users", async () => { for (const role of ["ADMIN", "STAFF", "LAWYER"] as const) { const user = await db.user.create({ data: { email: `${marker}.${role.toLowerCase()}@example.test`, name: `${marker} ${role}`, role, passwordHash: await hashPassword(password) } }); ids.push(user.id); if (role === "ADMIN") adminId = user.id; if (role === "STAFF") staffId = user.id; if (role === "LAWYER") lawyerId = user.id; } });
test.afterAll("clean controlled users", async () => { await db.auditLog.deleteMany({ where: { entityId: { in: ids } } }); await db.session.deleteMany({ where: { userId: { in: ids } } }); await db.user.deleteMany({ where: { id: { in: ids } } }); await db.$disconnect(); });
test("ADMIN manages controlled users", async ({ page }) => { await login(page, `${marker}.admin@example.test`); await page.goto("/admin/users"); await page.getByTestId("admin-users-search").fill(`${marker} STAFF`); const row = page.getByTestId(`admin-users-row-${staffId}`); await expect(row).toBeVisible(); await row.getByTestId(`admin-users-detail-${staffId}`).click(); await expect(page).toHaveURL(new RegExp(`/admin/users/${staffId}$`)); await page.getByTestId("user-edit").getByLabel("الاسم").fill(`${marker} Edited`); await page.getByTestId("user-edit").getByRole("button", { name: "حفظ الهوية" }).click(); await expect.poll(async () => (await db.user.findUnique({ where: { id: staffId } }))?.name).toBe(`${marker} Edited`); await selectValue(page.getByTestId("user-role-action"), "LAWYER"); await expect.poll(async () => (await db.user.findUnique({ where: { id: staffId } }))?.role).toBe("STAFF"); await page.getByRole("button", { name: "تغيير الدور", exact: true }).click(); const roleResponse = page.waitForResponse((response) => response.url().endsWith(`/admin/users/${staffId}/role`) && response.request().method() === "PATCH"); await page.getByTestId("user-role-confirm").click(); const response = await roleResponse; expect(response.status()).toBe(200); expect((await response.json()).data.role).toBe("LAWYER"); await expect.poll(async () => (await db.user.findUnique({ where: { id: staffId } }))?.role).toBe("LAWYER"); await expect(page.getByTestId("user-role-action")).toHaveAttribute("data-value", "LAWYER"); await expect.poll(async () => (await db.auditLog.findFirst({ where: { entityId: staffId, action: "USER_ROLE_CHANGED" }, orderBy: { createdAt: "desc" } }))?.metadata).toMatchObject({ oldRole: "STAFF", newRole: "LAWYER" }); await page.getByTestId("user-status-action").click(); await page.getByTestId("user-disable-confirm").click(); await expect.poll(async () => (await db.user.findUnique({ where: { id: staffId } }))?.isActive).toBe(false); expect(await db.session.count({ where: { userId: staffId, revokedAt: null } })).toBe(0); await page.getByTestId("user-password-reset").fill(nextPassword); await page.getByLabel("تأكيد كلمة المرور الجديدة").fill(nextPassword); await page.getByRole("button", { name: "إعادة تعيين كلمة المرور", exact: true }).click(); await expect.poll(async () => ((await db.user.findUnique({ where: { id: staffId } }))?.passwordHash !== nextPassword)).toBe(true); await expect.poll(async () => db.auditLog.count({ where: { entityId: staffId, action: { in: ["USER_UPDATED", "USER_ROLE_CHANGED", "USER_DISABLED", "USER_PASSWORD_RESET"] } } })).toBe(4); });
test("LAWYER cannot use Users Admin", async ({ page }) => { await login(page, `${marker}.lawyer@example.test`); await page.goto("/admin/users"); await expect(page.locator('[role="alert"]').filter({ hasText: "صلاحية مدير النظام" })).toBeVisible(); expect(await page.evaluate(async () => (await fetch("http://localhost:4000/api/v1/admin/users", { credentials: "include" })).status)).toBe(403); expect(lawyerId).not.toBe(""); expect(adminId).not.toBe(""); });
