import { expect, test, type Page, type Route } from "@playwright/test";
import type { AdminUserListItem } from "@hhlawyer/types";
import { usersContent } from "../src/features/admin/users/users-content";
import { selectValue } from "./select-helpers";

const admin={id:"users-admin",name:"Admin Operator",email:"admin@example.test",role:"ADMIN" as const};
const staff:AdminUserListItem={id:"users-staff",name:"Operations Staff",email:"staff@example.test",role:"STAFF",isActive:true,createdAt:"2099-01-01T08:00:00.000Z",updatedAt:"2099-01-02T08:00:00.000Z"};
const detail={...staff,lockedUntil:"2099-12-31T08:00:00.000Z",lastLoginAt:"2099-06-01T10:30:00.000Z"};
async function fulfill(route:Route,data:unknown,status=200,code="DATABASE_ERROR"){await route.fulfill({status,contentType:"application/json",body:JSON.stringify(status<400?{success:true,data}:{success:false,error:{code,message:"Safe test failure"}})});}
async function mockAuth(page:Page,user=admin){await page.route("**/api/v1/auth/me",route=>fulfill(route,{user}));}
function listData(items=[staff],page=1,total=42){return{items,pagination:{page,limit:20,total,totalPages:Math.ceil(total/20)}};}

test("Team directory uses bounded server queries, ephemeral search, URL filters, sort, and pagination",async({page})=>{const c=usersContent.en;const requests:URL[]=[];await mockAuth(page);await page.route("**/api/v1/admin/users?**",async route=>{const url=new URL(route.request().url());requests.push(url);await fulfill(route,listData([staff],Number(url.searchParams.get("page")??1)));});await page.goto("/en/admin/users");await expect(page.getByRole("heading",{level:1,name:c.title})).toBeVisible();await expect(page.getByTestId("admin-users-desktop-list")).toBeVisible();await selectValue(page.getByTestId("admin-users-role-filter"), "STAFF");await expect(page).toHaveURL(/role=STAFF/);await expect.poll(()=>requests.at(-1)?.searchParams.get("role")).toBe("STAFF");await selectValue(page.getByTestId("admin-users-status-filter"), "true");await expect.poll(()=>requests.at(-1)?.searchParams.get("isActive")).toBe("true");await selectValue(page.getByTestId("admin-users-sort"), "email:asc");await expect.poll(()=>`${requests.at(-1)?.searchParams.get("sortBy")}:${requests.at(-1)?.searchParams.get("sortOrder")}`).toBe("email:asc");await selectValue(page.getByTestId("admin-users-page-size"), "50");await expect.poll(()=>requests.at(-1)?.searchParams.get("limit")).toBe("50");await page.getByTestId("admin-users-search").fill(staff.email);await expect.poll(()=>requests.at(-1)?.searchParams.get("search"),{timeout:3000}).toBe(staff.email);expect(page.url()).not.toContain(staff.email);expect(requests.every(url=>Number(url.searchParams.get("limit")??20)<=50)).toBe(true);await page.getByTestId("admin-users-list").getByRole("button",{name:c.next,exact:true}).click();await expect.poll(()=>requests.at(-1)?.searchParams.get("page")).toBe("2");await selectValue(page.getByTestId("admin-users-role-filter"), "ADMIN");await expect(page).not.toHaveURL(/page=2/);const storage=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));expect(storage).not.toContain(staff.email);});

test("directory distinguishes loading, safe error retry, normal empty, and filtered empty",async({page})=>{const c=usersContent.en;let mode:"error"|"empty"="error";await mockAuth(page);await page.route("**/api/v1/admin/users?**",async route=>{await new Promise(resolve=>setTimeout(resolve,300));if(mode==="error")return fulfill(route,null,500);return fulfill(route,listData([],1,0));});await page.goto("/en/admin/users",{waitUntil:"domcontentloaded"});await expect(page.getByTestId("admin-users-loading")).toBeVisible();await expect(page.getByText(c.loadError)).toBeVisible();mode="empty";await page.getByRole("button",{name:c.retry}).click();await expect(page.getByText(c.empty)).toBeVisible();await selectValue(page.getByTestId("admin-users-role-filter"), "LAWYER");await expect(page.getByText(c.filteredEmpty)).toBeVisible();});

for(const width of [430,390,360])test(`Arabic team cards reflow without horizontal overflow at ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await mockAuth(page);await page.route("**/api/v1/admin/users?**",route=>fulfill(route,listData()));await page.goto("/ar/admin/users");const cards=page.getByTestId("admin-users-mobile-list");await expect(cards).toBeVisible();await expect(page.getByTestId("admin-users-desktop-list")).toBeHidden();await expect(cards.getByText(usersContent.ar.roles.STAFF)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});

test("create dialog validates fields, prevents duplicate submit, maps duplicate email, and clears password on close",async({page})=>{const c=usersContent.en;let posts=0;let resolvePost:undefined|(()=>void);await mockAuth(page);await page.route("**/api/v1/admin/users?**",route=>fulfill(route,listData()));await page.route("**/api/v1/admin/users",async route=>{if(route.request().method()!=="POST")return route.fallback();posts+=1;await new Promise<void>(resolve=>{resolvePost=resolve;});await fulfill(route,null,409,"USER_EMAIL_EXISTS");});await page.goto("/en/admin/users");const trigger=page.getByTestId("admin-users-create");await trigger.click();const dialog=page.getByRole("dialog");await page.getByTestId("create-user-submit").click();await expect(dialog.getByText(c.invalidName)).toBeVisible();await dialog.locator('input[autocomplete="name"]').fill("New User");await dialog.locator('input[type="email"]').fill("new@example.test");await dialog.locator('input[type="password"]').fill("secure password 123");await selectValue(page.getByTestId("create-user-role"), "LAWYER");await page.getByTestId("create-user-submit").click();await expect(page.getByTestId("create-user-submit")).toBeDisabled();await page.getByTestId("create-user-submit").click({force:true});expect(posts).toBe(1);resolvePost?.();await expect(dialog.getByText(c.duplicateEmail)).toBeVisible();await page.keyboard.press("Escape");await expect(trigger).toBeFocused();await trigger.click();await expect(page.getByRole("dialog").locator('input[type="password"]')).toHaveValue("");});

test("successful create refreshes the bounded directory and Dashboard user counts",async({page})=>{const c=usersContent.en;const created={...staff,id:"created-user",name:"Created Lawyer",email:"created@example.test",role:"LAWYER" as const};let items=[staff];let listReads=0;let overviewReads=0;await mockAuth(page);await page.route("**/api/v1/admin/overview?**",route=>{overviewReads+=1;return fulfill(route,{authenticated:true,period:{range:"30d",startsAt:"2099-01-01T00:00:00.000Z",endsAt:"2099-01-31T00:00:00.000Z"},consultations:{total:0,periodTotal:0,byStatus:{PENDING:0,CONFIRMED:0,RESCHEDULED:0,COMPLETED:0,CANCELLED:0}},contacts:{total:0,periodTotal:0,unread:0,byStatus:{UNREAD:0,READ:0,REPLIED:0,ARCHIVED:0}},services:{total:0,active:0,inactive:0},users:{total:items.length,active:items.length,inactive:0,byRole:{ADMIN:1,LAWYER:items.length-1,STAFF:0}},recentConsultations:[],recentContacts:[],recentActivity:[]});});await page.route("**/api/v1/admin/users?**",route=>{listReads+=1;return fulfill(route,listData(items,1,items.length));});await page.route("**/api/v1/admin/users",async route=>{if(route.request().method()!=="POST")return route.fallback();items=[...items,created];await fulfill(route,created,201);});await page.goto("/en/admin");await expect.poll(()=>overviewReads).toBe(1);await page.goto("/en/admin/users");await page.getByTestId("admin-users-create").click();const dialog=page.getByRole("dialog");await dialog.locator('input[autocomplete="name"]').fill(created.name);await dialog.locator('input[type="email"]').fill(created.email);await dialog.locator('input[type="password"]').fill("secure password 123");await selectValue(dialog.getByTestId("create-user-role"), "LAWYER");await dialog.getByTestId("create-user-submit").click();await expect(page.getByText(c.createdSuccess)).toBeVisible();await expect.poll(()=>listReads).toBeGreaterThan(1);await expect(page.getByTestId("admin-users-desktop-list").getByText(created.name)).toBeVisible();await page.getByRole("link",{name:"Overview",exact:true}).first().click();await expect.poll(()=>overviewReads).toBeGreaterThan(1);});

test("detail separates identity, security facts, role confirmation, status confirmation, and password confirmation",async({page})=>{const c=usersContent.en;let current={...detail};let roleCalls=0;let detailReads=0;await mockAuth(page);await page.route(`**/api/v1/admin/users/${staff.id}`,async route=>{detailReads+=1;if(route.request().method()==="PATCH"){current={...current,...await route.request().postDataJSON()};return fulfill(route,current);}await fulfill(route,current);});await page.route(`**/api/v1/admin/users/${staff.id}/role`,async route=>{roleCalls+=1;current={...current,role:(await route.request().postDataJSON()).role};await fulfill(route,current);});await page.route(`**/api/v1/admin/users/${staff.id}/status`,async route=>{current={...current,isActive:(await route.request().postDataJSON()).isActive};await fulfill(route,current);});await page.route(`**/api/v1/admin/users/${staff.id}/reset-password`,route=>fulfill(route,current));await page.goto(`/en/admin/users/${staff.id}`);await expect(page.getByRole("heading",{level:1,name:staff.name})).toBeVisible();await expect(page.getByText(c.lastLogin)).toBeVisible();await expect(page.getByText(c.lockedUntil)).toBeVisible();await selectValue(page.getByTestId("user-role-action"), "LAWYER");expect(roleCalls).toBe(0);await page.getByRole("button",{name:c.changeRole,exact:true}).click();await expect(page.getByRole("dialog")).toContainText(c.capabilities.LAWYER);await page.keyboard.press("Escape");expect(roleCalls).toBe(0);await page.getByRole("button",{name:c.changeRole,exact:true}).click();await page.getByTestId("user-role-confirm").click();await expect.poll(()=>roleCalls).toBe(1);await expect.poll(()=>detailReads).toBeGreaterThan(1);await page.getByTestId("user-status-action").click();await expect(page.getByRole("dialog")).toContainText(c.disableDescription);await page.getByTestId("user-disable-confirm").click();await expect.poll(()=>current.isActive).toBe(false);await page.getByTestId("user-password-reset").fill("another secure password");await page.getByLabel(c.confirmPassword).fill("different password value");await page.getByRole("button",{name:c.confirmReset,exact:true}).click();await expect(page.getByText(c.passwordMismatch)).toBeVisible();});

test("Last Admin and self-disable domain protections remain explicit and localized",async({page})=>{const c=usersContent.en;const self={...detail,...admin,isActive:true};await mockAuth(page);await page.route(`**/api/v1/admin/users/${admin.id}`,route=>fulfill(route,self));await page.route(`**/api/v1/admin/users/${admin.id}/role`,route=>fulfill(route,null,409,"LAST_ADMIN_PROTECTED"));await page.goto(`/en/admin/users/${admin.id}`);await expect(page.getByText(c.self)).toBeVisible();await expect(page.getByText(c.selfDisable)).toBeVisible();await expect(page.getByTestId("user-status-action")).toHaveCount(0);await selectValue(page.getByTestId("user-role-action"), "STAFF");await page.getByRole("button",{name:c.changeRole,exact:true}).click();await page.getByTestId("user-role-confirm").click();await expect(page.getByText(c.lastAdmin,{exact:true}).last()).toBeVisible();});

test("editing the current user identity invalidates auth/me for authoritative shell identity",async({page})=>{const c=usersContent.en;let authReads=0;let self={...detail,...admin,isActive:true};await page.route("**/api/v1/auth/me",route=>{authReads+=1;return fulfill(route,{user:{id:self.id,name:self.name,email:self.email,role:self.role}});});await page.route(`**/api/v1/admin/users/${admin.id}`,async route=>{if(route.request().method()==="PATCH")self={...self,...await route.request().postDataJSON()};await fulfill(route,self);});await page.goto(`/en/admin/users/${admin.id}`);const form=page.getByTestId("user-edit");await form.locator('input[autocomplete="name"]').fill("Updated Admin Identity");await form.getByRole("button",{name:c.saveIdentity}).click();await expect.poll(()=>authReads).toBeGreaterThan(1);await expect(page.getByText("Updated Admin Identity").first()).toBeVisible();});
