import { expect, test, type Page, type Route } from "@playwright/test";
import type { AdminServiceDetail, AdminServiceListItem, AuthUser } from "@hhlawyer/types";
import { servicesContent } from "../src/features/admin/services/services-content";
import { selectValue } from "./select-helpers";

const admin:AuthUser={id:"services-admin",name:"Admin Operator",email:"admin@example.test",role:"ADMIN"};
const mapped:AdminServiceListItem={id:"service-criminal",slug:"criminal",name:"Canonical Criminal",isActive:true,sortOrder:10,createdAt:"2099-01-01T08:00:00.000Z",updatedAt:"2099-01-02T08:00:00.000Z"};
const unmapped:AdminServiceListItem={id:"service-custom",slug:"custom-unmapped",name:"Canonical Custom",isActive:false,sortOrder:20,createdAt:"2099-01-03T08:00:00.000Z",updatedAt:"2099-01-04T08:00:00.000Z"};
const detail=(item:AdminServiceListItem):AdminServiceDetail=>({...item,description:`Canonical description for ${item.slug}.`});
async function fulfill(route:Route,data:unknown,status=200,code="DATABASE_ERROR"){await route.fulfill({status,contentType:"application/json",body:JSON.stringify(status<400?{success:true,data}:{success:false,error:{code,message:"Safe test failure"}})});}
async function mockAuth(page:Page,user=admin){await page.route("**/api/v1/auth/me",route=>fulfill(route,{user}));}
function listData(items:AdminServiceListItem[]=[mapped,unmapped],page=1,total=42,limit=20){const boundedTotal=total?Math.max(total,limit+1):0;return{items,pagination:{page,limit,total:boundedTotal,totalPages:Math.ceil(boundedTotal/limit)}};}

test("service catalogue uses bounded server queries, supported filters, sorting, and ephemeral search",async({page})=>{const c=servicesContent.en;const requests:URL[]=[];await mockAuth(page);await page.route("**/api/v1/admin/services?**",route=>{const url=new URL(route.request().url());requests.push(url);const limit=Number(url.searchParams.get("limit")??20);return fulfill(route,listData(undefined,Number(url.searchParams.get("page")??1),42,limit));});await page.goto("/en/admin/services");await expect(page.getByRole("heading",{level:1,name:c.title})).toBeVisible();await expect(page.getByTestId("admin-services-desktop-list")).toBeVisible();await expect(page.getByTestId(`service-row-${mapped.id}`)).toContainText(c.mapped);await expect(page.getByTestId(`service-row-${unmapped.id}`)).toContainText(c.missing);await selectValue(page.getByTestId("services-status-filter"), "true");await expect.poll(()=>requests.at(-1)?.searchParams.get("isActive")).toBe("true");await selectValue(page.getByTestId("services-sort"), "sortOrder:asc");await expect.poll(()=>`${requests.at(-1)?.searchParams.get("sortBy")}:${requests.at(-1)?.searchParams.get("sortOrder")}`).toBe("sortOrder:asc");await selectValue(page.getByTestId("services-page-size"), "50");await expect.poll(()=>requests.at(-1)?.searchParams.get("limit")).toBe("50");await page.getByTestId("services-search").fill(unmapped.slug);await expect.poll(()=>requests.at(-1)?.searchParams.get("search"),{timeout:3000}).toBe(unmapped.slug);expect(page.url()).not.toContain(unmapped.slug);expect(requests.every(url=>Number(url.searchParams.get("limit")??20)<=50)).toBe(true);await page.getByText(c.next,{exact:true}).click();await expect.poll(()=>requests.at(-1)?.searchParams.get("page")).toBe("2");await selectValue(page.getByTestId("services-status-filter"), "false");await expect(page).not.toHaveURL(/page=2/);});

test("services list distinguishes loading, safe error retry, normal empty, and filtered empty",async({page})=>{const c=servicesContent.en;let mode:"error"|"empty"="error";await mockAuth(page);await page.route("**/api/v1/admin/services?**",async route=>{await new Promise(resolve=>setTimeout(resolve,250));return mode==="error"?fulfill(route,null,500):fulfill(route,listData([],1,0));});await page.goto("/en/admin/services",{waitUntil:"domcontentloaded"});await expect(page.getByTestId("admin-services-loading")).toBeVisible();await expect(page.getByText(c.loadError)).toBeVisible();mode="empty";await page.getByRole("button",{name:c.retry}).click();await expect(page.getByText(c.empty)).toBeVisible();await selectValue(page.getByTestId("services-status-filter"), "false");await expect(page.getByText(c.filteredEmpty)).toBeVisible();});

for(const width of [430,390,360])test(`Arabic service cards reflow without horizontal overflow at ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await mockAuth(page);await page.route("**/api/v1/admin/services?**",route=>fulfill(route,listData()));await page.goto("/ar/admin/services");await expect(page.getByTestId("admin-services-mobile-list")).toBeVisible();await expect(page.getByTestId("admin-services-desktop-list")).toBeHidden();await expect(page.getByTestId(`service-card-${mapped.id}`)).toContainText(servicesContent.ar.mapped);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});

test("create dialog validates canonical fields, prevents duplicate submit, and never fabricates localization",async({page})=>{const c=servicesContent.en;let posts=0;let resolvePost:undefined|(()=>void);await mockAuth(page);await page.route("**/api/v1/admin/services?**",route=>fulfill(route,listData()));await page.route("**/api/v1/admin/services",async route=>{if(route.request().method()!=="POST")return route.fallback();posts+=1;await new Promise<void>(resolve=>{resolvePost=resolve;});await fulfill(route,null,409,"SERVICE_SLUG_EXISTS");});await page.goto("/en/admin/services");const trigger=page.getByTestId("services-create");await trigger.click();const dialog=page.getByRole("dialog");await page.getByTestId("service-create-submit").click();await expect(dialog.getByText(c.invalidSlug)).toBeVisible();await page.getByTestId("service-create-slug").fill("new-unmapped-service");await expect(dialog.getByText(c.missing)).toBeVisible();await page.getByTestId("service-create-name").fill("Canonical new service");await page.getByTestId("service-create-description").fill("Canonical description only.");await page.getByTestId("service-create-sort-order").fill("5");await page.getByTestId("service-create-submit").click();await expect(page.getByTestId("service-create-submit")).toBeDisabled();await page.getByTestId("service-create-submit").click({force:true});expect(posts).toBe(1);resolvePost?.();await expect(dialog.getByText(c.duplicateSlug)).toBeVisible();await page.keyboard.press("Escape");await expect(trigger).toBeFocused();});

test("successful creation refreshes directory and Dashboard metrics while preserving missing localization truth",async({page})=>{const c=servicesContent.en;const created:AdminServiceDetail={...detail(unmapped),id:"created-service",slug:"fresh-unmapped",name:"Fresh canonical"};let items=[mapped,unmapped];let listReads=0;let overviewReads=0;await mockAuth(page);await page.route("**/api/v1/admin/overview?**",route=>{overviewReads+=1;return fulfill(route,{authenticated:true,period:{range:"30d",startsAt:"2099-01-01T00:00:00.000Z",endsAt:"2099-01-31T00:00:00.000Z"},consultations:{total:0,periodTotal:0,byStatus:{PENDING:0,CONFIRMED:0,RESCHEDULED:0,COMPLETED:0,CANCELLED:0}},contacts:{total:0,periodTotal:0,unread:0,byStatus:{UNREAD:0,READ:0,REPLIED:0,ARCHIVED:0}},services:{total:items.length,active:1,inactive:items.length-1},users:{total:1,active:1,inactive:0,byRole:{ADMIN:1,LAWYER:0,STAFF:0}},recentConsultations:[],recentContacts:[],recentActivity:[]});});await page.route("**/api/v1/admin/services?**",route=>{listReads+=1;return fulfill(route,listData(items,1,items.length));});await page.route("**/api/v1/admin/services",async route=>{if(route.request().method()!=="POST")return route.fallback();items=[...items,created];return fulfill(route,created,201);});await page.goto("/en/admin");await expect.poll(()=>overviewReads).toBe(1);await page.goto("/en/admin/services");await page.getByTestId("services-create").click();await page.getByTestId("service-create-slug").fill(created.slug);await page.getByTestId("service-create-name").fill(created.name);await page.getByTestId("service-create-description").fill(created.description);await page.getByTestId("service-create-sort-order").fill("20");await page.getByTestId("service-create-submit").click();await expect(page.getByText(c.createdMissing)).toBeVisible();await expect.poll(()=>listReads).toBeGreaterThan(1);await expect(page.getByTestId("admin-services-desktop-list").getByText(created.name)).toBeVisible();await page.getByRole("link",{name:"Overview",exact:true}).first().click();await expect.poll(()=>overviewReads).toBeGreaterThan(1);});

test("mapped detail separates canonical editing, immutable slug, localization preview, and confirmed availability",async({page})=>{const c=servicesContent.en;let item=detail(mapped);let patchCount=0;await mockAuth(page);await page.route(`**/api/v1/admin/services/${mapped.id}`,async route=>{if(route.request().method()==="PATCH"){patchCount+=1;item={...item,...route.request().postDataJSON()};return fulfill(route,item);}return fulfill(route,item);});await page.route(`**/api/v1/admin/services/${mapped.id}/status`,async route=>{item={...item,isActive:route.request().postDataJSON().isActive};return fulfill(route,item);});await page.goto(`/en/admin/services/${mapped.id}`);await expect(page.getByTestId("service-localization")).toContainText("Criminal Law");await expect(page.getByTestId("service-localization")).toContainText("القانون الجنائي");await expect(page.getByTestId("service-public-preview-en")).toHaveAttribute("href",`/en/services/${mapped.slug}`);await expect(page.locator('input[value="criminal"]')).toHaveCount(0);const form=page.getByTestId("service-edit");await form.locator("input").first().fill("Updated canonical name");await form.getByRole("button",{name:c.save}).click();await expect.poll(()=>patchCount).toBe(1);await page.getByTestId("service-status-action").click();await page.keyboard.press("Escape");expect(item.isActive).toBe(true);await page.getByTestId("service-status-action").click();await page.getByTestId("service-disable-confirm").click();await expect.poll(()=>item.isActive).toBe(false);await page.getByTestId("service-status-action").click();await page.getByTestId("service-enable-confirm").click();await expect.poll(()=>item.isActive).toBe(true);});

test("unmapped detail shows truthful missing state without a broken public link",async({page})=>{const c=servicesContent.en;await mockAuth(page);await page.route(`**/api/v1/admin/services/${unmapped.id}`,route=>fulfill(route,detail(unmapped)));await page.goto(`/en/admin/services/${unmapped.id}`);await expect(page.getByTestId("service-localization-missing")).toContainText(c.missingDescription);await expect(page.getByTestId("service-localization").getByRole("link")).toHaveCount(0);await expect(page.getByTestId("admin-service-detail")).toContainText(unmapped.name);});

test("non-admin roles remain denied by the existing authority boundary",async({page})=>{await mockAuth(page,{...admin,role:"LAWYER" as const});let adminReads=0;await page.route("**/api/v1/admin/services?**",route=>{adminReads+=1;return fulfill(route,null,403,"FORBIDDEN");});await page.goto("/en/admin/services");await expect(page.locator('[role="alert"]').filter({hasText:servicesContent.en.unauthorized})).toBeVisible();expect(adminReads).toBe(0);});
