import { Router } from "express";
import type { Router as ExpressRouter } from "express";
import type { PrismaClient } from "@prisma/client";
import { adminContactListSchema, contactStatusUpdateSchema } from "@hhlawyer/validation";
import { AppError } from "../../middleware/error-handler.js";
import { requireApprovedOrigin } from "../../middleware/origin.js";
import { requireAuth, requirePermission, type AuthRequest } from "../auth/auth.routes.js";

const transitions={UNREAD:["READ","ARCHIVED"],READ:["UNREAD","REPLIED","ARCHIVED"],REPLIED:["ARCHIVED"],ARCHIVED:[]} as const;
const listSelect={id:true,name:true,email:true,subject:true,status:true,createdAt:true,updatedAt:true} as const;
const detailSelect={...listSelect,message:true} as const;
export function createAdminContactRouter(database:PrismaClient):ExpressRouter { const router=Router(); router.use("/admin",requireAuth(database));
router.get("/admin/contacts",requirePermission("CONTACT_READ"),async(req,res,next)=>{const parsed=adminContactListSchema.safeParse(req.query);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid contact query."));const v=parsed.data;const where={...(v.status?{status:v.status}:{}),...(v.search?{OR:["name","email","subject"].map(field=>({[field]:{contains:v.search,mode:"insensitive" as const}}))}:{})};try{const [items,total]=await Promise.all([database.contactMessage.findMany({where,skip:(v.page-1)*v.limit,take:v.limit,orderBy:{[v.sortBy]:v.sortOrder},select:listSelect}),database.contactMessage.count({where})]);res.json({success:true,data:{items,pagination:{page:v.page,limit:v.limit,total,totalPages:Math.ceil(total/v.limit)}}});}catch{next(new AppError(500,"DATABASE_ERROR","Unable to load contact messages."));}});
router.get("/admin/contacts/:id",requirePermission("CONTACT_READ"),async(req,res,next)=>{try{const item=await database.contactMessage.findUnique({where:{id:Array.isArray(req.params.id)?req.params.id[0]:req.params.id},select:detailSelect});if(!item)return next(new AppError(404,"CONTACT_MESSAGE_NOT_FOUND","Contact message was not found."));res.json({success:true,data:item});}catch{next(new AppError(500,"DATABASE_ERROR","Unable to load contact message."));}});
router.patch("/admin/contacts/:id/status",requireApprovedOrigin,requirePermission("CONTACT_MANAGE"),async(req:AuthRequest,res,next)=>{const parsed=contactStatusUpdateSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid contact status."));try{const item=await database.$transaction(async tx=>{const current=await tx.contactMessage.findUnique({where:{id:Array.isArray(req.params.id)?req.params.id[0]:req.params.id}});if(!current)throw new AppError(404,"CONTACT_MESSAGE_NOT_FOUND","Contact message was not found.");if(current.status===parsed.data.status)return current;if(!transitions[current.status].includes(parsed.data.status as never))throw new AppError(409,"INVALID_CONTACT_STATUS_TRANSITION","This contact status transition is not allowed.");const updated=await tx.contactMessage.update({where:{id:current.id},data:{status:parsed.data.status}});await tx.auditLog.create({data:{userId:req.auth!.id,action:"CONTACT_STATUS_CHANGED",entity:"ContactMessage",entityId:current.id,metadata:{oldStatus:current.status,newStatus:parsed.data.status}}});return updated;});res.json({success:true,data:{id:item.id,status:item.status}});}catch(error){next(error);}});return router;}
