import type { Locale } from "@/i18n/locale";

const en={
title:"Services",description:"Manage consultation availability and the canonical metadata stored for each legal service.",addService:"Add service",search:"Search canonical name or slug",filters:"Filters",clear:"Clear filters",status:"Consultation availability",sort:"Sort",all:"All",active:"Active",inactive:"Inactive",newest:"Newest",oldest:"Oldest",nameAsc:"Name A–Z",nameDesc:"Name Z–A",orderAsc:"Catalogue order",slugAsc:"Slug A–Z",pageSize:"Rows per page",results:(from:string,to:string,total:string)=>`${from}–${to} of ${total} services`,previous:"Previous",next:"Next",page:(page:string,total:string)=>`Page ${page} of ${total}`,
canonicalName:"Canonical name",slug:"Public slug",availability:"Availability",localization:"Public localization",mapped:"Localized content available",missing:"Localization mapping missing",order:"Order",created:"Created",manage:"Manage service",loading:"Loading services",loadError:"Services could not be loaded",retry:"Try again",empty:"No services have been created",filteredEmpty:"No services match these filters",unauthorized:"Administrator access is required to manage services.",forbidden:"You do not have permission to perform this action.",genericError:"The request could not be completed safely. Try again.",notFound:"This service could not be found.",validation:"Review the highlighted fields and try again.",duplicateSlug:"A service already uses this slug.",
createTitle:"Add a canonical service",createDescription:"Create the operational service record used by consultation booking. Public Arabic and English copy is maintained separately.",canonicalNote:"These fields are canonical service metadata. They do not create or edit public Arabic or English copy.",name:"Service name",descriptionLabel:"Description",slugHelp:"Lowercase letters, numbers, and hyphens only. The slug becomes a stable public routing and localization key and cannot be edited later.",descriptionHelp:"Stored with the canonical service record; mapped public descriptions remain separate.",orderHelp:"Lower numbers appear first in API-driven service selection.",activeHelp:"Active services are available in API-driven consultation selection.",create:"Create service",creating:"Creating…",cancel:"Cancel",close:"Close dialog",createdSuccess:"Service created successfully.",createdMissing:"The service was created, but this slug has no public localization mapping.",invalidSlug:"Use lowercase letters, numbers, and hyphens only.",invalidName:"Enter a service name.",invalidDescription:"Enter a service description.",invalidOrder:"Enter a whole number from 0 to 1,000,000.",
details:"Service details",back:"Services",identity:"Service identity",identityDescription:"Stable routing and record facts for this canonical service.",updated:"Last updated",immutableSlug:"The slug is fixed after creation because it is used as a public route and localization key.",canonicalMetadata:"Canonical service metadata",canonicalDescription:"Stored on the service record and separate from the curated public website content.",save:"Save canonical metadata",saving:"Saving…",saved:"Canonical metadata updated.",publicContent:"Public website content",publicDescription:"This read-only preview comes from the approved Arabic and English website content map.",separationNote:"Editing canonical metadata here does not automatically update the localized public-site copy.",arabicPreview:"Arabic public preview",englishPreview:"English public preview",viewPublic:"View public service",missingTitle:"No public localization mapping",missingDescription:"The canonical service exists, but this slug has no curated Arabic/English website content or valid public detail route. API consumers may still use canonical list data where supported.",
availabilityTitle:"Consultation availability",availabilityDescription:"This state controls whether the service is returned by the active-services API for new consultation selection. Existing records are preserved.",disable:"Make unavailable",enable:"Make available",disableTitle:"Make this service unavailable?",enableTitle:"Make this service available?",disableDescription:"The service will be removed from API-driven consultation selection for new requests. Existing consultations and canonical data remain preserved.",enableDescription:"The service will return to API-driven consultation selection for new requests.",confirmDisable:"Confirm unavailable",confirmEnable:"Confirm available",statusChanged:"Service availability updated.",technical:"Routing and ordering",technicalDescription:"The immutable slug identifies routes/localization; numeric order affects API-driven service ordering.",
};

const ar:typeof en={
title:"الخدمات",description:"إدارة إتاحة الخدمات للاستشارات والبيانات الأساسية المحفوظة لكل خدمة قانونية.",addService:"إضافة خدمة",search:"البحث بالاسم الأساسي أو المعرّف",filters:"عوامل التصفية",clear:"مسح عوامل التصفية",status:"الإتاحة للاستشارات",sort:"الترتيب",all:"الكل",active:"نشطة",inactive:"غير نشطة",newest:"الأحدث",oldest:"الأقدم",nameAsc:"الاسم أبجديًا",nameDesc:"الاسم عكسيًا",orderAsc:"ترتيب الكتالوج",slugAsc:"المعرّف أبجديًا",pageSize:"عدد الصفوف",results:(from,to,total)=>`${from}–${to} من ${total} خدمة`,previous:"السابق",next:"التالي",page:(page,total)=>`صفحة ${page} من ${total}`,
canonicalName:"الاسم الأساسي",slug:"معرّف الرابط",availability:"الإتاحة",localization:"ترجمة الموقع",mapped:"المحتوى المترجم متوفر",missing:"ترجمة الموقع غير متوفرة",order:"الترتيب",created:"تاريخ الإنشاء",manage:"إدارة الخدمة",loading:"جارٍ تحميل الخدمات",loadError:"تعذر تحميل الخدمات",retry:"إعادة المحاولة",empty:"لم تُنشأ خدمات بعد",filteredEmpty:"لا توجد خدمات تطابق عوامل التصفية",unauthorized:"يلزم امتلاك صلاحية مدير النظام لإدارة الخدمات.",forbidden:"ليست لديك صلاحية لتنفيذ هذا الإجراء.",genericError:"تعذر إتمام الطلب بأمان. حاول مرة أخرى.",notFound:"تعذر العثور على هذه الخدمة.",validation:"راجع الحقول المحددة وحاول مرة أخرى.",duplicateSlug:"توجد خدمة تستخدم معرّف الرابط هذا بالفعل.",
createTitle:"إضافة خدمة أساسية",createDescription:"أنشئ سجل الخدمة التشغيلي المستخدم في حجز الاستشارات. يُدار المحتوى العربي والإنجليزي للموقع بشكل منفصل.",canonicalNote:"هذه حقول بيانات الخدمة الأساسية، ولا تنشئ أو تعدّل النص العربي أو الإنجليزي المنشور في الموقع.",name:"اسم الخدمة",descriptionLabel:"الوصف",slugHelp:"استخدم حروفًا إنجليزية صغيرة وأرقامًا وشرطات فقط. يصبح المعرّف مفتاحًا ثابتًا للرابط والترجمة ولا يمكن تعديله لاحقًا.",descriptionHelp:"يُحفظ مع سجل الخدمة الأساسي، بينما تظل أوصاف الموقع المترجمة منفصلة.",orderHelp:"تظهر الأرقام الأصغر أولًا في قوائم الخدمات المعتمدة على API.",activeHelp:"تتاح الخدمات النشطة للاختيار في طلبات الاستشارة المعتمدة على API.",create:"إنشاء الخدمة",creating:"جارٍ الإنشاء…",cancel:"إلغاء",close:"إغلاق النافذة",createdSuccess:"تم إنشاء الخدمة بنجاح.",createdMissing:"تم إنشاء الخدمة، لكن معرّفها غير مرتبط بمحتوى مترجم للموقع.",invalidSlug:"استخدم حروفًا إنجليزية صغيرة وأرقامًا وشرطات فقط.",invalidName:"أدخل اسم الخدمة.",invalidDescription:"أدخل وصف الخدمة.",invalidOrder:"أدخل عددًا صحيحًا من 0 إلى 1,000,000.",
details:"تفاصيل الخدمة",back:"الخدمات",identity:"هوية الخدمة",identityDescription:"حقائق الرابط والسجل الثابتة لهذه الخدمة الأساسية.",updated:"آخر تحديث",immutableSlug:"معرّف الرابط ثابت بعد الإنشاء لأنه يُستخدم في الرابط العام ومفتاح الترجمة.",canonicalMetadata:"بيانات الخدمة الأساسية",canonicalDescription:"محفوظة في سجل الخدمة ومنفصلة عن محتوى الموقع المنسق.",save:"حفظ البيانات الأساسية",saving:"جارٍ الحفظ…",saved:"تم تحديث البيانات الأساسية.",publicContent:"محتوى الموقع",publicDescription:"هذه معاينة للقراءة فقط من خريطة المحتوى العربي والإنجليزي المعتمدة للموقع.",separationNote:"تعديل بيانات الخدمة الأساسية هنا لا يحدّث تلقائيًا النص المترجم المنشور في الموقع.",arabicPreview:"معاينة الموقع بالعربية",englishPreview:"معاينة الموقع بالإنجليزية",viewPublic:"عرض الخدمة في الموقع",missingTitle:"لا توجد ترجمة مرتبطة بالموقع",missingDescription:"الخدمة الأساسية موجودة، لكن هذا المعرّف لا يملك محتوى عربيًا/إنجليزيًا منسقًا أو صفحة تفاصيل عامة صالحة. قد تستمر واجهات API المدعومة في استخدام البيانات الأساسية.",
availabilityTitle:"الإتاحة للاستشارات",availabilityDescription:"تحدد هذه الحالة ظهور الخدمة في واجهة الخدمات النشطة واختيارها لطلبات الاستشارة الجديدة، مع الحفاظ على السجلات الحالية.",disable:"جعلها غير متاحة",enable:"جعلها متاحة",disableTitle:"جعل هذه الخدمة غير متاحة؟",enableTitle:"جعل هذه الخدمة متاحة؟",disableDescription:"ستُزال الخدمة من اختيار الاستشارات الجديدة المعتمد على API، مع بقاء الاستشارات السابقة والبيانات الأساسية محفوظة.",enableDescription:"ستعود الخدمة إلى اختيار الاستشارات الجديدة المعتمد على API.",confirmDisable:"تأكيد عدم الإتاحة",confirmEnable:"تأكيد الإتاحة",statusChanged:"تم تحديث إتاحة الخدمة.",technical:"الرابط والترتيب",technicalDescription:"يعرّف المعرّف الثابت الرابط والترجمة، ويؤثر الرقم في ترتيب الخدمات المعتمد على API.",
};

export const servicesContent:Record<Locale,typeof en>={en,ar};
