"use client";

import { LibraryBig, RefreshCw } from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AdminDataState, AdminPage, AdminPageHeader } from "@/components/admin/foundation";
import { localizePath, useLocale } from "@/components/providers/LocaleProvider";
import { formatLocaleNumber } from "@/i18n/format";
import { adminDashboardKeys } from "@/lib/api/admin-dashboard";
import { adminServicesKeys, createAdminService, getAdminServices, type AdminServicesFilters } from "@/lib/api/admin-services";
import { currentUser } from "@/lib/api/auth";
import { ApiClientError } from "@/lib/api/client";
import { CreateServiceDialog } from "./CreateServiceDialog";
import { ServiceRecords } from "./ServiceRecords";
import { ServicesToolbar } from "./ServicesToolbar";
import { defaultServiceFilters, serviceError, serviceFiltersFromSearchParams, serviceFiltersToSearchParams, serviceLocalization } from "./services-model";
import { servicesContent } from "./services-content";
import styles from "./Services.module.css";

export function ServicesListPage(){const locale=useLocale();const c=servicesContent[locale];const router=useRouter();const pathname=usePathname();const params=useSearchParams();const client=useQueryClient();const urlFilters=useMemo(()=>serviceFiltersFromSearchParams(new URLSearchParams(params.toString())),[params]);const [searchInput,setSearchInput]=useState("");const [search,setSearch]=useState("");const [createOpen,setCreateOpen]=useState(false);const [feedback,setFeedback]=useState("");const [createdId,setCreatedId]=useState("");
const me=useQuery({queryKey:["auth","me"],queryFn:currentUser,retry:false});const filters=useMemo(()=>({...urlFilters,...(search?{search}:{})}),[search,urlFilters]);const services=useQuery({enabled:me.data?.user.role==="ADMIN",queryKey:adminServicesKeys.list(filters),queryFn:({signal})=>getAdminServices(filters,signal),retry:1});useEffect(()=>{const timer=window.setTimeout(()=>setSearch(searchInput.trim()),400);return()=>window.clearTimeout(timer);},[searchInput]);useEffect(()=>{if(me.isError||(me.isSuccess&&!me.data))router.replace(localizePath("/admin/login",locale));},[locale,me.data,me.isError,me.isSuccess,router]);
const navigate=(next:AdminServicesFilters)=>{const nextParams=serviceFiltersToSearchParams(next);router.replace(nextParams.size?`${pathname}?${nextParams}`:pathname,{scroll:false});};const update=(change:Partial<AdminServicesFilters>)=>navigate({...urlFilters,...change,page:change.page??1});const clear=()=>{setSearchInput("");setSearch("");navigate(defaultServiceFilters);};const create=useMutation({mutationFn:createAdminService,retry:false,onSuccess:async item=>{setCreatedId(item.id);setCreateOpen(false);setFeedback(serviceLocalization(item.slug).mapped?c.createdSuccess:c.createdMissing);await Promise.all([client.invalidateQueries({queryKey:adminServicesKeys.all}),client.invalidateQueries({queryKey:adminDashboardKeys.all}),client.invalidateQueries({queryKey:["services","active"]}),client.invalidateQueries({queryKey:["active-services"]})]);},onError:error=>setFeedback(serviceError(error instanceof ApiClientError?error.error.code:undefined,c))});
if(me.isLoading)return <ServicesListSkeleton locale={locale}/>;if(!me.data)return null;if(me.data.user.role!=="ADMIN")return <AdminPage><AdminDataState description={c.unauthorized} title={c.forbidden} tone="error"/></AdminPage>;const pagination=services.data?.pagination;const from=pagination&&pagination.total?(pagination.page-1)*pagination.limit+1:0;const to=pagination?Math.min(pagination.page*pagination.limit,pagination.total):0;const activeCount=Number(urlFilters.isActive!==undefined)+Number(urlFilters.limit!==20)+Number(urlFilters.sortBy!=="createdAt"||urlFilters.sortOrder!=="desc");
return <AdminPage className={styles.page} data-testid="admin-services-list"><AdminPageHeader actions={<CreateServiceDialog key={createdId||"new"} error={create.isError?feedback:undefined} locale={locale} onOpenChange={value=>{setFeedback("");setCreateOpen(value);}} onSubmit={value=>{setFeedback("");create.mutate(value);}} open={createOpen} pending={create.isPending}/>} description={c.description} title={c.title}/><ServicesToolbar activeCount={activeCount} filters={urlFilters} locale={locale} onChange={update} onClear={clear} onSearch={value=>{setSearchInput(value);if(urlFilters.page!==1)update({page:1});}} search={searchInput}/>{feedback&&!createOpen?<p className={styles.successFeedback} role="status">{feedback}</p>:null}{services.isLoading?<ServicesListSkeleton embedded locale={locale}/>:services.isError?<div className={styles.stateWrap}><AdminDataState description={c.genericError} title={c.loadError} tone="error"/><button onClick={()=>void services.refetch()} type="button"><RefreshCw aria-hidden="true" size={16}/>{c.retry}</button></div>:services.data?<section aria-labelledby="services-results" className={styles.results}><div className={styles.resultsHeader}><h2 id="services-results">{c.title}</h2><p>{c.results(formatLocaleNumber(from,locale),formatLocaleNumber(to,locale),formatLocaleNumber(services.data.pagination.total,locale))}</p></div>{services.data.items.length?<><ServiceRecords items={services.data.items} locale={locale}/><nav aria-label={c.page(formatLocaleNumber(services.data.pagination.page,locale),formatLocaleNumber(services.data.pagination.totalPages,locale))} className={styles.pagination}><button disabled={urlFilters.page<=1} onClick={()=>update({page:urlFilters.page-1})}>{c.previous}</button><p>{c.page(formatLocaleNumber(services.data.pagination.page,locale),formatLocaleNumber(services.data.pagination.totalPages,locale))}</p><button disabled={urlFilters.page>=services.data.pagination.totalPages} onClick={()=>update({page:urlFilters.page+1})}>{c.next}</button></nav></>:<div className={styles.stateWrap}><LibraryBig aria-hidden="true" size={24}/><AdminDataState title={searchInput.trim()||activeCount?c.filteredEmpty:c.empty}/>{searchInput.trim()||activeCount?<button onClick={clear}>{c.clear}</button>:null}</div>}</section>:null}</AdminPage>;}

export function ServicesListSkeleton({embedded=false,locale}:{embedded?:boolean;locale:"ar"|"en"}){const content=<div aria-label={servicesContent[locale].loading} aria-busy="true" className={styles.skeleton} data-testid="admin-services-loading"><span/><span/><span/><span/></div>;return embedded?content:<AdminPage>{content}</AdminPage>;}
