import type { AdminServiceDetail, AdminServiceUpdateInput } from "@hhlawyer/types";
import { Eye, FilePenLine, Globe2, Power, Route } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { AdminDialogContent, AdminSectionTitle, AdminSurface, AdminTechnicalValue } from "@/components/admin/foundation";
import { localizePath } from "@/components/providers/LocaleProvider";
import { Dialog, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { formatLocaleDateTime } from "@/i18n/format";
import type { Locale } from "@/i18n/locale";
import { AvailabilityBadge, LocalizationBadge } from "./ServiceBadges";
import { serviceLocalization } from "./services-model";
import { servicesContent } from "./services-content";
import styles from "./Services.module.css";

type Pending="metadata"|"status"|null;type Errors=Partial<Record<"name"|"description"|"sortOrder",string>>;
export function ServiceDetailSections({error,item,locale,onMetadata,onStatus,pending}:{error:string;item:AdminServiceDetail;locale:Locale;onMetadata:(value:AdminServiceUpdateInput)=>void;onStatus:(value:boolean)=>Promise<boolean>;pending:Pending}){const c=servicesContent[locale];const localized=serviceLocalization(item.slug);const [name,setName]=useState(item.name);const [description,setDescription]=useState(item.description);const [sortOrder,setSortOrder]=useState(item.sortOrder);const [errors,setErrors]=useState<Errors>({});const [statusOpen,setStatusOpen]=useState(false);const dirty=name.trim()!==item.name||description.trim()!==item.description||sortOrder!==item.sortOrder;const submit=()=>{const next:Errors={};if(!name.trim()||name.trim().length>160)next.name=c.invalidName;if(!description.trim()||description.trim().length>4000)next.description=c.invalidDescription;if(!Number.isInteger(sortOrder)||sortOrder<0||sortOrder>1_000_000)next.sortOrder=c.invalidOrder;setErrors(next);if(Object.keys(next).length)return;onMetadata({name:name.trim(),description:description.trim(),sortOrder});};
return <div className={styles.detailGrid}>
<AdminSurface className={styles.identitySurface}><div className={styles.sectionHeading}><span><Route aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.identity}</AdminSectionTitle><p>{c.identityDescription}</p></div></div><dl className={styles.facts}><div><dt>{c.slug}</dt><dd><AdminTechnicalValue>{item.slug}</AdminTechnicalValue></dd></div><div><dt>{c.created}</dt><dd>{formatLocaleDateTime(item.createdAt,locale)}</dd></div><div><dt>{c.updated}</dt><dd>{formatLocaleDateTime(item.updatedAt,locale)}</dd></div></dl><p className={styles.canonicalNotice}>{c.immutableSlug}</p></AdminSurface>
<AdminSurface className={styles.metadataSurface}><div className={styles.sectionHeading}><span><FilePenLine aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.canonicalMetadata}</AdminSectionTitle><p>{c.canonicalDescription}</p></div></div><p className={styles.separationNote}>{c.separationNote}</p><form className={styles.formGrid} data-testid="service-edit" noValidate onSubmit={e=>{e.preventDefault();submit();}}><label><span>{c.name}</span><input aria-invalid={Boolean(errors.name)} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/>{errors.name?<small role="alert">{errors.name}</small>:null}</label><label><span>{c.descriptionLabel}</span><textarea aria-invalid={Boolean(errors.description)} maxLength={4000} rows={7} value={description} onChange={e=>setDescription(e.target.value)}/><small>{c.descriptionHelp}</small>{errors.description?<small role="alert">{errors.description}</small>:null}</label><label><span>{c.order}</span><input aria-invalid={Boolean(errors.sortOrder)} inputMode="numeric" min={0} max={1_000_000} type="number" value={sortOrder} onChange={e=>setSortOrder(Number(e.target.value))}/><small>{c.orderHelp}</small>{errors.sortOrder?<small role="alert">{errors.sortOrder}</small>:null}</label><button className={styles.primaryButton} disabled={Boolean(pending)||!dirty} type="submit">{pending==="metadata"?c.saving:c.save}</button></form></AdminSurface>
<AdminSurface className={styles.localizationSurface} data-testid="service-localization"><div className={styles.sectionHeading}><span><Globe2 aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.publicContent}</AdminSectionTitle><p>{c.publicDescription}</p></div></div><div className={styles.coverageHeading}><LocalizationBadge locale={locale} mapped={localized.mapped}/></div>{localized.mapped?<div className={styles.previewGrid}><article dir="rtl"><p>{c.arabicPreview}</p><h3>{localized.ar.title}</h3><span>{localized.ar.description}</span><Link data-testid="service-public-preview-ar" href={localizePath(`/services/${item.slug}`,"ar")}><Eye aria-hidden="true" size={16}/>{c.viewPublic}</Link></article><article dir="ltr"><p>{c.englishPreview}</p><h3>{localized.en.title}</h3><span>{localized.en.description}</span><Link data-testid="service-public-preview-en" href={localizePath(`/services/${item.slug}`,"en")}><Eye aria-hidden="true" size={16}/>{c.viewPublic}</Link></article></div>:<div className={styles.missingLocalization} data-testid="service-localization-missing"><strong>{c.missingTitle}</strong><p>{c.missingDescription}</p></div>}<p className={styles.separationNote}>{c.separationNote}</p></AdminSurface>
<AdminSurface className={styles.availabilitySurface}><div className={styles.sectionHeading}><span><Power aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.availabilityTitle}</AdminSectionTitle><p>{c.availabilityDescription}</p></div></div><div className={styles.availabilityAction}><AvailabilityBadge active={item.isActive} locale={locale}/><Dialog open={statusOpen} onOpenChange={value=>{if(pending!=="status")setStatusOpen(value);}}><DialogTrigger asChild><button className={item.isActive?styles.attentionButton:styles.primaryButton} data-testid="service-status-action" disabled={Boolean(pending)} type="button">{item.isActive?c.disable:c.enable}</button></DialogTrigger><AdminDialogContent closeLabel={c.close}><DialogTitle>{item.isActive?c.disableTitle:c.enableTitle}</DialogTitle><DialogDescription>{item.isActive?c.disableDescription:c.enableDescription}</DialogDescription><div className={styles.dialogActions}><button disabled={pending==="status"} onClick={()=>setStatusOpen(false)}>{c.cancel}</button><button className={item.isActive?styles.attentionButton:styles.primaryButton} data-testid={item.isActive?"service-disable-confirm":"service-enable-confirm"} disabled={pending==="status"} onClick={async()=>{if(await onStatus(!item.isActive))setStatusOpen(false);}}>{item.isActive?c.confirmDisable:c.confirmEnable}</button></div></AdminDialogContent></Dialog></div></AdminSurface>
<AdminSurface className={styles.technicalSurface}><div className={styles.sectionHeading}><span><Route aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.technical}</AdminSectionTitle><p>{c.technicalDescription}</p></div></div><dl className={styles.facts}><div><dt>{c.slug}</dt><dd><AdminTechnicalValue>{item.slug}</AdminTechnicalValue></dd></div><div><dt>{c.order}</dt><dd><AdminTechnicalValue>{item.sortOrder}</AdminTechnicalValue></dd></div></dl></AdminSurface>
{error?<p className={styles.errorFeedback} role="alert">{error}</p>:null}
</div>;}
