import { Filter, Search } from "lucide-react";
import type { Locale } from "@/i18n/locale";
import type { AdminServicesFilters } from "@/lib/api/admin-services";
import { servicesContent } from "./services-content";
import styles from "./Services.module.css";

export function ServicesToolbar({activeCount,filters,locale,onChange,onClear,onSearch,search}:{activeCount:number;filters:AdminServicesFilters;locale:Locale;onChange:(value:Partial<AdminServicesFilters>)=>void;onClear:()=>void;onSearch:(value:string)=>void;search:string}){const c=servicesContent[locale];return <section aria-label={c.filters} className={styles.toolbar}>
  <label><span>{c.search}</span><span className={styles.searchControl}><Search aria-hidden="true" size={17}/><input data-testid="services-search" autoComplete="off" type="search" value={search} onChange={e=>onSearch(e.target.value)}/></span></label>
  <div className={styles.filters}><label><span>{c.status}</span><select data-testid="services-status-filter" value={filters.isActive===undefined?"":String(filters.isActive)} onChange={e=>onChange({isActive:e.target.value===""?undefined:e.target.value==="true"})}><option value="">{c.all}</option><option value="true">{c.active}</option><option value="false">{c.inactive}</option></select></label><label><span>{c.sort}</span><select data-testid="services-sort" value={`${filters.sortBy}:${filters.sortOrder}`} onChange={e=>{const [sortBy,sortOrder]=e.target.value.split(":") as [AdminServicesFilters["sortBy"],AdminServicesFilters["sortOrder"]];onChange({sortBy,sortOrder});}}><option value="createdAt:desc">{c.newest}</option><option value="createdAt:asc">{c.oldest}</option><option value="name:asc">{c.nameAsc}</option><option value="name:desc">{c.nameDesc}</option><option value="sortOrder:asc">{c.orderAsc}</option><option value="slug:asc">{c.slugAsc}</option></select></label><label><span>{c.pageSize}</span><select data-testid="services-page-size" value={filters.limit} onChange={e=>onChange({limit:Number(e.target.value)})}><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></label></div>
  {activeCount?<div className={styles.activeFilters}><span><Filter aria-hidden="true" size={15}/>{activeCount}</span><button type="button" onClick={onClear}>{c.clear}</button></div>:null}
</section>;}
