import { Prisma, type PrismaClient, type UserRole } from "@prisma/client";
import { Router, type Router as ExpressRouter } from "express";
import { adminUserCreateSchema, adminUserResetPasswordSchema, adminUserRoleUpdateSchema, adminUsersListQuerySchema, adminUserStatusUpdateSchema, adminUserUpdateSchema } from "@hhlawyer/validation";
import { AppError } from "../../middleware/error-handler.js";
import { requireApprovedOrigin } from "../../middleware/origin.js";
import { hashPassword } from "./auth.service.js";
import { requireAuth, requirePermission, type AuthRequest } from "./auth.routes.js";

const safeSelect={id:true,name:true,email:true,role:true,isActive:true,createdAt:true,updatedAt:true,lockedUntil:true,lastLoginAt:true} as const;
const listSelect={id:true,name:true,email:true,role:true,isActive:true,createdAt:true,updatedAt:true} as const;
const isUnique=(error:unknown)=>error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002";
const isSerialization=(error:unknown)=>error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2034";
const notFound=()=>new AppError(404,"USER_NOT_FOUND","User was not found.");
const routeId=(value:string|string[])=>Array.isArray(value)?value[0]:value;
const audit=(tx:Prisma.TransactionClient,userId:string,action:string,entityId:string,metadata?:Prisma.InputJsonValue)=>tx.auditLog.create({data:{userId,action,entity:"User",entityId,metadata}});

async function protectLastAdmin(tx:Prisma.TransactionClient,target:{id:string;role:UserRole;isActive:boolean},next:{role?:UserRole;isActive?:boolean}) {
  const remainsAdmin=(next.role??target.role)==="ADMIN"&&(next.isActive??target.isActive);
  if (target.role!=="ADMIN"||!target.isActive||remainsAdmin) return;
  if (await tx.user.count({where:{role:"ADMIN",isActive:true}})<=1) throw new AppError(409,"LAST_ADMIN_PROTECTED","At least one active ADMIN must remain.");
}

export function createAdminUsersRouter(database:PrismaClient):ExpressRouter {
  const router=Router(); router.use("/admin/users",requireAuth(database),requirePermission("USER_MANAGE"));
  router.get("/admin/users",async(req,res,next)=>{const parsed=adminUsersListQuerySchema.safeParse(req.query);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid user query."));const v=parsed.data;const where={...(v.role?{role:v.role}:{}),...(v.isActive===undefined?{}:{isActive:v.isActive}),...(v.search?{OR:["name","email"].map(field=>({[field]:{contains:v.search,mode:"insensitive" as const}}))}:{})};try{const[items,total]=await Promise.all([database.user.findMany({where,skip:(v.page-1)*v.limit,take:v.limit,orderBy:{[v.sortBy]:v.sortOrder},select:listSelect}),database.user.count({where})]);res.json({success:true,data:{items,pagination:{page:v.page,limit:v.limit,total,totalPages:Math.ceil(total/v.limit)}}});}catch{next(new AppError(500,"DATABASE_ERROR","Unable to load users."));}});
  router.get("/admin/users/:id",async(req,res,next)=>{try{const item=await database.user.findUnique({where:{id:routeId(req.params.id)},select:safeSelect});if(!item)throw notFound();res.json({success:true,data:item});}catch(error){next(error instanceof AppError?error:new AppError(500,"DATABASE_ERROR","Unable to load user."));}});
  router.post("/admin/users",requireApprovedOrigin,async(req:AuthRequest,res,next)=>{const parsed=adminUserCreateSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid user payload."));try{const item=await database.$transaction(async tx=>{const user=await tx.user.create({data:{name:parsed.data.name,email:parsed.data.email,role:parsed.data.role,passwordHash:await hashPassword(parsed.data.password)},select:safeSelect});await audit(tx,req.auth!.id,"USER_CREATED",user.id,{role:user.role});return user;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});res.status(201).json({success:true,data:item});}catch(error){next(isUnique(error)?new AppError(409,"USER_EMAIL_EXISTS","A user with this email already exists."):new AppError(500,"DATABASE_ERROR","Unable to create user."));}});
  router.patch("/admin/users/:id",requireApprovedOrigin,async(req:AuthRequest,res,next)=>{const parsed=adminUserUpdateSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid user payload."));try{const item=await database.$transaction(async tx=>{const current=await tx.user.findUnique({where:{id:routeId(req.params.id)},select:safeSelect});if(!current)throw notFound();const changed=Object.entries(parsed.data).some(([key,value])=>current[key as "name"|"email"]!==value);if(!changed)return current;const user=await tx.user.update({where:{id:current.id},data:parsed.data,select:safeSelect});await audit(tx,req.auth!.id,"USER_UPDATED",user.id);return user;});res.json({success:true,data:item});}catch(error){next(error instanceof AppError?error:isUnique(error)?new AppError(409,"USER_EMAIL_EXISTS","A user with this email already exists."):new AppError(500,"DATABASE_ERROR","Unable to update user."));}});
  router.patch("/admin/users/:id/role",requireApprovedOrigin,async(req:AuthRequest,res,next)=>{const parsed=adminUserRoleUpdateSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid role payload."));try{const item=await database.$transaction(async tx=>{const current=await tx.user.findUnique({where:{id:routeId(req.params.id)},select:safeSelect});if(!current)throw notFound();if(current.role===parsed.data.role)return current;await protectLastAdmin(tx,current,{role:parsed.data.role});const user=await tx.user.update({where:{id:current.id},data:{role:parsed.data.role},select:safeSelect});await audit(tx,req.auth!.id,"USER_ROLE_CHANGED",user.id,{oldRole:current.role,newRole:user.role});return user;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});res.json({success:true,data:item});}catch(error){next(error instanceof AppError?error:isSerialization(error)?new AppError(409,"LAST_ADMIN_PROTECTED","At least one active ADMIN must remain."):new AppError(500,"DATABASE_ERROR","Unable to update user role."));}});
  router.patch("/admin/users/:id/status",requireApprovedOrigin,async(req:AuthRequest,res,next)=>{const parsed=adminUserStatusUpdateSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid status payload."));try{const item=await database.$transaction(async tx=>{const current=await tx.user.findUnique({where:{id:routeId(req.params.id)},select:safeSelect});if(!current)throw notFound();if(current.isActive===parsed.data.isActive)return current;await protectLastAdmin(tx,current,{isActive:parsed.data.isActive});if(!parsed.data.isActive&&req.auth!.id===current.id)throw new AppError(409,"CANNOT_DISABLE_SELF","An ADMIN cannot disable their own account.");const user=await tx.user.update({where:{id:current.id},data:{isActive:parsed.data.isActive},select:safeSelect});if(!user.isActive)await tx.session.updateMany({where:{userId:user.id,revokedAt:null},data:{revokedAt:new Date()}});await audit(tx,req.auth!.id,user.isActive?"USER_ENABLED":"USER_DISABLED",user.id,{oldIsActive:current.isActive,newIsActive:user.isActive});return user;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});res.json({success:true,data:item});}catch(error){next(error instanceof AppError?error:isSerialization(error)?new AppError(409,"LAST_ADMIN_PROTECTED","At least one active ADMIN must remain."):new AppError(500,"DATABASE_ERROR","Unable to update user status."));}});
  router.post("/admin/users/:id/reset-password",requireApprovedOrigin,async(req:AuthRequest,res,next)=>{const parsed=adminUserResetPasswordSchema.safeParse(req.body);if(!parsed.success)return next(new AppError(400,"VALIDATION_ERROR","Invalid password payload."));try{const item=await database.$transaction(async tx=>{const current=await tx.user.findUnique({where:{id:routeId(req.params.id)},select:safeSelect});if(!current)throw notFound();const user=await tx.user.update({where:{id:current.id},data:{passwordHash:await hashPassword(parsed.data.newPassword),failedLoginAttempts:0,lockedUntil:null},select:safeSelect});await tx.session.updateMany({where:{userId:user.id,revokedAt:null},data:{revokedAt:new Date()}});await audit(tx,req.auth!.id,"USER_PASSWORD_RESET",user.id);return user;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});res.json({success:true,data:item});}catch(error){next(error instanceof AppError?error:new AppError(500,"DATABASE_ERROR","Unable to reset password."));}});
  return router;
}
