import type { Locale } from "@/i18n/locale";

const en = {
  title:"Team & Access",description:"Manage internal accounts and access securely.",addUser:"Add user",search:"Search by name or email",filters:"Filters",clear:"Clear filters",role:"Role",status:"Account status",sort:"Sort",all:"All",active:"Active",inactive:"Inactive",newest:"Newest",nameAsc:"Name A–Z",emailAsc:"Email A–Z",roleAsc:"Role",pageSize:"Rows per page",results:(from:string,to:string,total:string)=>`${from}–${to} of ${total} users`,previous:"Previous",next:"Next",page:(page:string,total:string)=>`Page ${page} of ${total}`,
  name:"Name",email:"Email",lastLogin:"Last login",neverLoggedIn:"Never signed in",created:"Created",manage:"Manage access",self:"Your account",locked:"Temporarily locked",loading:"Loading team accounts",loadError:"Team accounts could not be loaded",retry:"Try again",empty:"No team accounts yet",filteredEmpty:"No accounts match these filters",unauthorized:"Administrator access is required to manage team accounts.",
  createTitle:"Add an internal user",createDescription:"Create an account with the minimum access needed for this person’s work.",password:"Temporary password",passwordHelp:"Use 12–512 characters. Share it through an approved secure channel.",create:"Create user",cancel:"Cancel",creating:"Creating…",createdSuccess:"User created successfully.",duplicateEmail:"An account already uses this email address.",invalidName:"Enter a name of at least 2 characters.",invalidEmail:"Enter a valid email address.",invalidPassword:"Enter a password of at least 12 characters.",
  details:"User account",back:"Team & Access",identity:"Identity",identityDescription:"The name and email shown across the admin workspace.",saveIdentity:"Save identity",saving:"Saving…",identitySaved:"Identity updated.",access:"Access",accessDescription:"Choose a proposed role, review its permissions, then confirm the change.",changeRole:"Change role",roleDialogTitle:"Confirm role change",roleDialogDescription:"This changes what this person can access in the admin workspace.",currentRole:"Current role",newRole:"New role",confirmRole:"Confirm role change",roleChanged:"Role updated.",lastAdmin:"At least one active Administrator must remain.",
  security:"Security state",securityDescription:"Current authentication and account facts exposed by the secure user record.",notLocked:"No temporary login lock",lockedUntil:"Temporary lock until",sensitive:"Sensitive actions",sensitiveDescription:"These actions affect account access and active sessions.",disable:"Disable account",enable:"Enable account",disableTitle:"Disable this account?",enableTitle:"Enable this account?",disableDescription:"The account will lose access immediately and all active sessions will be revoked.",enableDescription:"The account will be permitted to sign in again.",confirmDisable:"Confirm disable",confirmEnable:"Confirm enable",statusChanged:"Account status updated.",selfDisable:"You cannot disable the account you are currently using.",
  resetPassword:"Reset password",resetDescription:"Set a replacement password. All active sessions for this account will be revoked.",newPassword:"New password",confirmPassword:"Confirm new password",passwordMismatch:"The passwords do not match.",confirmReset:"Reset password",passwordReset:"Password reset and active sessions revoked.",notFound:"This user could not be found.",genericError:"The request could not be completed safely. Try again.",forbidden:"You do not have permission to perform this action.",validation:"Review the highlighted fields and try again.",
  roles:{ADMIN:"Administrator",LAWYER:"Lawyer",STAFF:"Staff"},capabilities:{ADMIN:"Full administrative management, including users and services.",LAWYER:"Manage consultation workflows and read client messages; no user or service administration.",STAFF:"Manage message workflows and read consultations; no user or service administration."},close:"Close dialog",
};

const ar: typeof en = {
  title:"الفريق والصلاحيات",description:"إدارة الحسابات الداخلية وصلاحيات الوصول بأمان.",addUser:"إضافة مستخدم",search:"البحث بالاسم أو البريد الإلكتروني",filters:"عوامل التصفية",clear:"مسح عوامل التصفية",role:"الدور",status:"حالة الحساب",sort:"الترتيب",all:"الكل",active:"نشط",inactive:"غير نشط",newest:"الأحدث",nameAsc:"الاسم أبجديًا",emailAsc:"البريد أبجديًا",roleAsc:"الدور",pageSize:"عدد الصفوف",results:(from,to,total)=>`${from}–${to} من ${total} مستخدم`,previous:"السابق",next:"التالي",page:(page,total)=>`صفحة ${page} من ${total}`,
  name:"الاسم",email:"البريد الإلكتروني",lastLogin:"آخر تسجيل دخول",neverLoggedIn:"لم يسجل الدخول بعد",created:"تاريخ الإنشاء",manage:"إدارة الصلاحيات",self:"حسابك الحالي",locked:"مقفل مؤقتًا",loading:"جارٍ تحميل حسابات الفريق",loadError:"تعذر تحميل حسابات الفريق",retry:"إعادة المحاولة",empty:"لا توجد حسابات فريق بعد",filteredEmpty:"لا توجد حسابات تطابق عوامل التصفية",unauthorized:"يلزم امتلاك صلاحية مدير النظام لإدارة حسابات الفريق.",
  createTitle:"إضافة مستخدم داخلي",createDescription:"أنشئ حسابًا بأقل صلاحيات لازمة لأداء مهام هذا الشخص.",password:"كلمة مرور مؤقتة",passwordHelp:"استخدم من 12 إلى 512 حرفًا وشاركها عبر قناة آمنة معتمدة.",create:"إنشاء المستخدم",cancel:"إلغاء",creating:"جارٍ الإنشاء…",createdSuccess:"تم إنشاء المستخدم بنجاح.",duplicateEmail:"يوجد حساب يستخدم هذا البريد الإلكتروني بالفعل.",invalidName:"أدخل اسمًا من حرفين على الأقل.",invalidEmail:"أدخل بريدًا إلكترونيًا صحيحًا.",invalidPassword:"أدخل كلمة مرور من 12 حرفًا على الأقل.",
  details:"حساب المستخدم",back:"الفريق والصلاحيات",identity:"الهوية",identityDescription:"الاسم والبريد الظاهران في مساحة الإدارة.",saveIdentity:"حفظ الهوية",saving:"جارٍ الحفظ…",identitySaved:"تم تحديث الهوية.",access:"الصلاحيات",accessDescription:"اختر الدور المقترح وراجع صلاحياته ثم أكد التغيير.",changeRole:"تغيير الدور",roleDialogTitle:"تأكيد تغيير الدور",roleDialogDescription:"يؤثر هذا التغيير في ما يستطيع هذا الشخص الوصول إليه داخل مساحة الإدارة.",currentRole:"الدور الحالي",newRole:"الدور الجديد",confirmRole:"تأكيد تغيير الدور",roleChanged:"تم تحديث الدور.",lastAdmin:"يجب أن يظل هناك مدير نظام نشط واحد على الأقل.",
  security:"الحالة الأمنية",securityDescription:"حقائق المصادقة والحساب الحالية التي يتيحها سجل المستخدم الآمن.",notLocked:"لا يوجد قفل مؤقت لتسجيل الدخول",lockedUntil:"قفل مؤقت حتى",sensitive:"إجراءات حساسة",sensitiveDescription:"تؤثر هذه الإجراءات في الوصول إلى الحساب والجلسات النشطة.",disable:"تعطيل الحساب",enable:"تفعيل الحساب",disableTitle:"تعطيل هذا الحساب؟",enableTitle:"تفعيل هذا الحساب؟",disableDescription:"سيفقد الحساب الوصول فورًا وستُنهى جميع جلساته النشطة.",enableDescription:"سيُسمح للحساب بتسجيل الدخول مرة أخرى.",confirmDisable:"تأكيد التعطيل",confirmEnable:"تأكيد التفعيل",statusChanged:"تم تحديث حالة الحساب.",selfDisable:"لا يمكنك تعطيل الحساب الذي تستخدمه حاليًا.",
  resetPassword:"إعادة تعيين كلمة المرور",resetDescription:"عيّن كلمة مرور بديلة. ستُنهى جميع الجلسات النشطة لهذا الحساب.",newPassword:"كلمة المرور الجديدة",confirmPassword:"تأكيد كلمة المرور الجديدة",passwordMismatch:"كلمتا المرور غير متطابقتين.",confirmReset:"إعادة تعيين كلمة المرور",passwordReset:"تمت إعادة تعيين كلمة المرور وإنهاء الجلسات النشطة.",notFound:"تعذر العثور على هذا المستخدم.",genericError:"تعذر إتمام الطلب بأمان. حاول مرة أخرى.",forbidden:"ليست لديك صلاحية لتنفيذ هذا الإجراء.",validation:"راجع الحقول المحددة وحاول مرة أخرى.",
  roles:{ADMIN:"مدير النظام",LAWYER:"محامٍ",STAFF:"موظف"},capabilities:{ADMIN:"إدارة إدارية كاملة، بما في ذلك المستخدمون والخدمات.",LAWYER:"إدارة سير الاستشارات وقراءة رسائل العملاء، دون إدارة المستخدمين أو الخدمات.",STAFF:"إدارة سير الرسائل وقراءة الاستشارات، دون إدارة المستخدمين أو الخدمات."},close:"إغلاق النافذة",
};

export const usersContent: Record<Locale, typeof en> = { en, ar };
