import { Filter, Search } from "lucide-react";
import type { AdminUsersFilters } from "@/lib/api/admin-users";
import type { Locale } from "@/i18n/locale";
import { roles } from "./users-model";
import { usersContent } from "./users-content";
import styles from "./Users.module.css";

export function UsersToolbar({activeCount,filters,locale,onChange,onClear,onSearch,search}:{activeCount:number;filters:AdminUsersFilters;locale:Locale;onChange:(value:Partial<AdminUsersFilters>)=>void;onClear:()=>void;onSearch:(value:string)=>void;search:string}){const c=usersContent[locale];return <section aria-label={c.filters} className={styles.toolbar}>
  <label className={styles.searchField}><span>{c.search}</span><span className={styles.searchControl}><Search aria-hidden="true" size={17}/><input data-testid="admin-users-search" type="search" autoComplete="off" value={search} onChange={e=>onSearch(e.target.value)}/></span></label>
  <div className={styles.filters}><label><span>{c.role}</span><select data-testid="admin-users-role-filter" value={filters.role??""} onChange={e=>onChange({role:(e.target.value||undefined) as AdminUsersFilters["role"]})}><option value="">{c.all}</option>{roles.map(role=><option key={role} value={role}>{c.roles[role]}</option>)}</select></label><label><span>{c.status}</span><select data-testid="admin-users-status-filter" value={filters.isActive===undefined?"":String(filters.isActive)} onChange={e=>onChange({isActive:e.target.value===""?undefined:e.target.value==="true"})}><option value="">{c.all}</option><option value="true">{c.active}</option><option value="false">{c.inactive}</option></select></label><label><span>{c.sort}</span><select data-testid="admin-users-sort" value={`${filters.sortBy}:${filters.sortOrder}`} onChange={e=>{const [sortBy,sortOrder]=e.target.value.split(":") as [AdminUsersFilters["sortBy"],AdminUsersFilters["sortOrder"]];onChange({sortBy,sortOrder});}}><option value="createdAt:desc">{c.newest}</option><option value="name:asc">{c.nameAsc}</option><option value="email:asc">{c.emailAsc}</option><option value="role:asc">{c.roleAsc}</option></select></label><label><span>{c.pageSize}</span><select data-testid="admin-users-page-size" value={filters.limit} onChange={e=>onChange({limit:Number(e.target.value)})}><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></label></div>
  {activeCount?<div className={styles.activeFilters}><span><Filter aria-hidden="true" size={15}/>{activeCount}</span><button type="button" onClick={onClear}>{c.clear}</button></div>:null}
  </section>;}
