import type { AdminUserDetail, UserRole } from "@hhlawyer/types";
import { KeyRound, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { useRef, useState } from "react";
import { AdminDialogContent, AdminSectionTitle, AdminSurface } from "@/components/admin/foundation";
import { Dialog, DialogDescription, DialogTitle, DialogTrigger, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui";
import type { Locale } from "@/i18n/locale";
import { formatLocaleDateTime } from "@/i18n/format";
import { AccountBadge, RoleBadge } from "./UserBadges";
import { roles } from "./users-model";
import { usersContent } from "./users-content";
import styles from "./Users.module.css";

type Pending="identity"|"role"|"status"|"password"|null;
export function UserDetailSections({error,item,locale,onIdentity,onPassword,onRole,onStatus,pending,self}:{error:string;item:AdminUserDetail;locale:Locale;onIdentity:(v:{name:string;email:string})=>void;onPassword:(v:string)=>void;onRole:(v:UserRole)=>Promise<boolean>;onStatus:(v:boolean)=>Promise<boolean>;pending:Pending;self:boolean}){const c=usersContent[locale];const [name,setName]=useState(item.name);const [email,setEmail]=useState(item.email);const [proposedRole,setProposedRole]=useState<UserRole>(item.role);const [roleOpen,setRoleOpen]=useState(false);const [statusOpen,setStatusOpen]=useState(false);const [password,setPassword]=useState("");const [confirmation,setConfirmation]=useState("");const [identityError,setIdentityError]=useState<"name"|"email"|null>(null);const [passwordError,setPasswordError]=useState<"password"|"confirmation"|null>(null);const nameRef=useRef<HTMLInputElement>(null);const emailRef=useRef<HTMLInputElement>(null);const passwordRef=useRef<HTMLInputElement>(null);const confirmationRef=useRef<HTMLInputElement>(null);const locked=Boolean(item.lockedUntil&&new Date(item.lockedUntil)>new Date());
return <div className={styles.detailGrid}>
  <AdminSurface className={styles.identitySurface}><div className={styles.sectionHeading}><span><UserRound aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.identity}</AdminSectionTitle><p>{c.identityDescription}</p></div></div><form data-testid="user-edit" className={styles.formGrid} noValidate onSubmit={e=>{e.preventDefault();if(name.trim().length<2){setIdentityError("name");nameRef.current?.focus();return;}if(!/^\S+@\S+\.\S+$/.test(email)){setIdentityError("email");emailRef.current?.focus();return;}setIdentityError(null);onIdentity({name:name.trim(),email:email.trim()});}}><label><span>{c.name}</span><input ref={nameRef} aria-describedby={identityError==="name"?"user-identity-name-error":undefined} aria-invalid={identityError==="name"} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/>{identityError==="name"?<small id="user-identity-name-error" role="alert">{c.invalidName}</small>:null}</label><label><span>{c.email}</span><input ref={emailRef} aria-describedby={identityError==="email"?"user-identity-email-error":undefined} aria-invalid={identityError==="email"} autoComplete="email" dir="ltr" type="email" value={email} onChange={e=>setEmail(e.target.value)}/>{identityError==="email"?<small id="user-identity-email-error" role="alert">{c.invalidEmail}</small>:null}</label><button className={styles.primaryButton} disabled={Boolean(pending)||(name.trim()===item.name&&email.trim()===item.email)} type="submit">{pending==="identity"?c.saving:c.saveIdentity}</button></form></AdminSurface>
  <AdminSurface className={styles.accessSurface}><div className={styles.sectionHeading}><span><ShieldCheck aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.access}</AdminSectionTitle><p>{c.accessDescription}</p></div></div><div className={styles.roleEditor}><label><span>{c.role}</span><Select disabled={Boolean(pending)} value={proposedRole} onValueChange={(value)=>setProposedRole(value as UserRole)}><SelectTrigger aria-label={c.role} data-testid="user-role-action"><SelectValue /></SelectTrigger><SelectContent>{roles.map((role)=><SelectItem key={role} value={role}>{c.roles[role]}</SelectItem>)}</SelectContent></Select></label><p>{c.capabilities[proposedRole]}</p><Dialog open={roleOpen} onOpenChange={setRoleOpen}><DialogTrigger asChild><button disabled={Boolean(pending)||proposedRole===item.role} type="button">{c.changeRole}</button></DialogTrigger><AdminDialogContent closeLabel={c.close}><DialogTitle>{c.roleDialogTitle}</DialogTitle><DialogDescription>{c.roleDialogDescription}</DialogDescription><div className={styles.confirmationContext}><strong>{item.name}</strong><div><span>{c.currentRole}</span><RoleBadge locale={locale} role={item.role}/></div><p>{c.capabilities[item.role]}</p><div><span>{c.newRole}</span><RoleBadge locale={locale} role={proposedRole}/></div><p>{c.capabilities[proposedRole]}</p>{item.role==="ADMIN"&&proposedRole!=="ADMIN"?<p className={styles.constraint}>{c.lastAdmin}</p>:null}</div><div className={styles.dialogActions}><button disabled={pending==="role"} onClick={()=>setRoleOpen(false)}>{c.cancel}</button><button className={styles.primaryButton} data-testid="user-role-confirm" disabled={pending==="role"} onClick={async()=>{if(await onRole(proposedRole))setRoleOpen(false);}}>{c.confirmRole}</button></div></AdminDialogContent></Dialog></div></AdminSurface>
  <AdminSurface className={styles.securitySurface}><div className={styles.sectionHeading}><span><LockKeyhole aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.security}</AdminSectionTitle><p>{c.securityDescription}</p></div></div><dl className={styles.securityFacts}><div><dt>{c.status}</dt><dd><AccountBadge active={item.isActive} locale={locale}/></dd></div><div><dt>{c.lastLogin}</dt><dd>{item.lastLoginAt?formatLocaleDateTime(item.lastLoginAt,locale):c.neverLoggedIn}</dd></div><div><dt>{locked?c.lockedUntil:c.locked}</dt><dd>{locked&&item.lockedUntil?formatLocaleDateTime(item.lockedUntil,locale):c.notLocked}</dd></div></dl></AdminSurface>
  <AdminSurface className={styles.sensitiveSurface}><div className={styles.sectionHeading}><span><KeyRound aria-hidden="true" size={19}/></span><div><AdminSectionTitle>{c.sensitive}</AdminSectionTitle><p>{c.sensitiveDescription}</p></div></div><div className={styles.sensitiveBlocks}><section><h3>{item.isActive?c.disable:c.enable}</h3><p>{item.isActive?c.disableDescription:c.enableDescription}</p>{self&&item.isActive?<p className={styles.constraint}>{c.selfDisable}</p>:<Dialog open={statusOpen} onOpenChange={setStatusOpen}><DialogTrigger asChild><button className={item.isActive?styles.dangerButton:styles.primaryButton} data-testid="user-status-action" disabled={Boolean(pending)} type="button">{item.isActive?c.disable:c.enable}</button></DialogTrigger><AdminDialogContent closeLabel={c.close}><DialogTitle>{item.isActive?c.disableTitle:c.enableTitle}</DialogTitle><DialogDescription>{item.isActive?c.disableDescription:c.enableDescription}</DialogDescription><div className={styles.dialogActions}><button disabled={pending==="status"} onClick={()=>setStatusOpen(false)}>{c.cancel}</button><button className={item.isActive?styles.dangerButton:styles.primaryButton} data-testid={item.isActive?"user-disable-confirm":"user-enable-confirm"} disabled={pending==="status"} onClick={async()=>{if(await onStatus(!item.isActive))setStatusOpen(false);}}>{item.isActive?c.confirmDisable:c.confirmEnable}</button></div></AdminDialogContent></Dialog>}</section><section><h3>{c.resetPassword}</h3><p>{c.resetDescription}</p><form className={styles.formGrid} noValidate onSubmit={e=>{e.preventDefault();if(password.length<12){setPasswordError("password");passwordRef.current?.focus();return;}if(password!==confirmation){setPasswordError("confirmation");confirmationRef.current?.focus();return;}setPasswordError(null);onPassword(password);setPassword("");setConfirmation("");}}><label><span>{c.newPassword}</span><input ref={passwordRef} aria-describedby={passwordError==="password"?"user-password-error":undefined} aria-invalid={passwordError==="password"} data-testid="user-password-reset" autoComplete="new-password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{passwordError==="password"?<small id="user-password-error" role="alert">{c.invalidPassword}</small>:null}</label><label><span>{c.confirmPassword}</span><input ref={confirmationRef} aria-describedby={passwordError==="confirmation"?"user-password-confirmation-error":undefined} aria-invalid={passwordError==="confirmation"} autoComplete="new-password" type="password" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/>{passwordError==="confirmation"?<small id="user-password-confirmation-error" role="alert">{c.passwordMismatch}</small>:null}</label><button disabled={Boolean(pending)} type="submit">{pending==="password"?c.saving:c.confirmReset}</button></form></section></div></AdminSurface>
  {error?<p className={styles.errorFeedback} role="alert">{error}</p>:null}
</div>;}
