import type { UserRole } from "@hhlawyer/types";
import type { AdminUsersFilters } from "@/lib/api/admin-users";

export const roles: UserRole[] = ["ADMIN","LAWYER","STAFF"];
export const defaultUserFilters: AdminUsersFilters = { page:1, limit:20, sortBy:"createdAt", sortOrder:"desc" };
const sorts = new Set(["createdAt:desc","name:asc","email:asc","role:asc"]);
export function filtersFromSearchParams(params:URLSearchParams):AdminUsersFilters { const page=Math.max(1,Number(params.get("page"))||1); const limit=[10,20,50].includes(Number(params.get("limit")))?Number(params.get("limit")):20; const role=roles.includes(params.get("role") as UserRole)?params.get("role") as UserRole:undefined; const active=params.get("isActive"); const sort=sorts.has(params.get("sort")??"")?params.get("sort")!:"createdAt:desc"; const [sortBy,sortOrder]=sort.split(":") as [AdminUsersFilters["sortBy"],AdminUsersFilters["sortOrder"]]; return {page,limit,sortBy,sortOrder,...(role?{role}:{}),...(active==="true"||active==="false"?{isActive:active==="true"}:{})}; }
export function filtersToSearchParams(filters:AdminUsersFilters){const params=new URLSearchParams();if(filters.page!==1)params.set("page",String(filters.page));if(filters.limit!==20)params.set("limit",String(filters.limit));if(filters.role)params.set("role",filters.role);if(filters.isActive!==undefined)params.set("isActive",String(filters.isActive));if(filters.sortBy!=="createdAt"||filters.sortOrder!=="desc")params.set("sort",`${filters.sortBy}:${filters.sortOrder}`);return params;}
export function userError(code:string|undefined,copy:{duplicateEmail:string;lastAdmin:string;selfDisable:string;forbidden:string;notFound:string;validation:string;genericError:string}){switch(code){case"USER_EMAIL_EXISTS":return copy.duplicateEmail;case"LAST_ADMIN_PROTECTED":return copy.lastAdmin;case"CANNOT_DISABLE_SELF":return copy.selfDisable;case"FORBIDDEN":case"UNAUTHORIZED":return copy.forbidden;case"USER_NOT_FOUND":return copy.notFound;case"VALIDATION_ERROR":return copy.validation;default:return copy.genericError;}}
